[DBZ-2912] Add support for binary.handling.mode to the SQL Server connector
debezium/debezium pull request #2044
Opened 2021-01-12 00:06 UTC by morozov

- [x] Pass binary handling mode from configuration to the converter provider. The provider already supports it since it extends the JDBC converter provider.
- [x] Copy/paste documentation from the MySQL connector.

2021-01-12 01:04 UTC, morozov commented
The build failure looks irrelevant:

> 2021-01-12 00:52:39.23 spid51      Couldn't remove the user 5 from database 5 from the external libraries folder, error: 0x80070003

2021-01-13 13:12 UTC, gunnarmorling commented
Thx! Could you please:

* Add `io.debezium.config.CommonConnectorConfig.BINARY_HANDLING_MODE` to `ALL_FIELDS` and `configDef()` in the SQL Server connector config type (akin to the other connectors supporting this).
* Add a test (you can look for usages of the option in test code and take that test as a template)

2021-01-13 13:13 UTC, gunnarmorling requested changes
Good start, thx! A few comments inline.

2021-01-13 13:13 UTC, gunnarmorling commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|[[mysql-property-binary-handling-mode]]<<mysql-property-binary-handling-mode, `binary.handling.mode`>>
mysql -> sqlserver

2021-01-16 09:58 UTC, gunnarmorling commented
Excellent, thanks a lot!

2021-01-16 09:58 UTC, merged

2021-01-16 21:43 UTC, morozov commented
Thanks for the guidance, @gunnarmorling!