DBZ-3201 WIP testsuite docker container
debezium/debezium pull request #2338
Opened 2021-05-03 08:07 UTC by novotnyJiri

2021-05-04 10:14 UTC, jcechace commented on jenkins-jobs/docker/debezium-testing-opneshift/testsuite-deployment.sh
> +echo finished
I'd also like to see the file either segmented (put an empty line here and there ) or actually move things into functions to improve readability

2021-05-20 15:21 UTC, gunnarmorling commented
Hey @jpechane, @novotnyJiri, what's needed for un-WIP-ing this?

2021-05-24 21:52 UTC, jcechace requested changes

2021-05-27 09:08 UTC, jcechace requested changes

2021-05-27 09:08 UTC, jcechace commented on jenkins-jobs/docker/debezium-testing-opneshift/testsuite-deployment.sh
> +. /testsuite/library.sh
prefer  ``source`` over execution  for example new environment variables would not to be propagated back to the original shell)

2021-05-27 09:08 UTC, jcechace commented on jenkins-jobs/docker/debezium-testing-opneshift/library.sh
> +            --strimzi_downstream ) STRIMZI_DOWNSTREAM_URL=$2;      shift 2;;
lets be consistent and use ``--strimzi-downstream``

2021-05-27 09:45 UTC, jcechace approved these changes
LGTM.

@jpechane  Can you have a quick look in case I missed something important?

2021-06-01 06:59 UTC, jpechane commented
@novotnyJiri Just a cosmetic question - why the multiple empty lines at the end of files?

2021-06-02 12:33 UTC, novotnyJiri commented
> @novotnyJiri Just a cosmetic question - why the multiple empty lines at the end of files?

I must have left them there when refactoring, will fix it right away.

2021-06-02 14:56 UTC, merged