remove the parts of Kafka API, extend to support none kafka system
debezium/debezium pull request #2427
Opened 2021-05-28 02:41 UTC by lqjack

2021-05-28 08:03 UTC, Naros requested changes
There is quite a lot to digest here and we'll try and give this a proper review next week, but in the meantime I did do a quick look over the changes and I've commented on a few changes that don't quite make sense.  Could you please take a look at those.  

Also, could you please update the commit message to start with the issue number "DBZ-3571" and please rebase your changes against the current master to resolve conflicts.

2021-05-28 08:03 UTC, Naros commented on debezium-ddl-parser/src/test/resources/mysql/examples/bitrix_queries_cut.sql
> -#begin 1
Why was the DDL parser SQL examples that are used to test the DDL parser with removed?

2021-05-31 06:22 UTC, lqjack commented
@Naros thank you review the patch. I have reverted the developed code .

2021-06-07 13:20 UTC, gunnarmorling commented
Hey @lqjack, before talking about specifics of the implementation, can we take a step back and clarify _what_ exactly you'd like to achieve here, and _why_ you'd like to do this? Once we have reached agreement on that goal and that it is a worthy one, let's then think about the _how_. Thanks a lot for providing some context!

2021-06-08 16:16 UTC, lqjack commented
@gunnarmorling 

_why you'd like to do this?_

   1, We need the CDC feature as a standalone one.  In this way we can construct the Flink connector based on Debezium to support the CDC features without rework them. 

  2,  The current work is one the way to remove the Apache Kafka related API.  We want to provide the option for user to choose whether they need the feature based on the Kafka platform.

2021-06-08 16:17 UTC, lqjack commented
@gunnarmorling 

_why you'd like to do this?_

   1, We need the CDC feature as a standalone one.  In this way we can construct the Flink connector based on Debezium to support the CDC features without rework them. 

  2,  The current work is one the way to remove the Apache Kafka related API.  We want to provide the option for user to choose whether they need the feature based on the Kafka platform.

2021-06-09 19:22 UTC, derekm commented
@lqjack -- Have you seen https://github.com/ververica/flink-cdc-connectors ? It uses Debezium Engine and is very similar to Debezium Server (in fact, it would be cool to see Debezium Server improve such that Ververica's flink-cdc-connectors could be refactored into a proper Debezium Server sink).

2021-06-10 03:48 UTC, lqjack commented
@derekm thanks the rely, I will check the repo.

2021-06-16 08:40 UTC, closed without merging