DBZ-3650 jenkins job for building rhel kafka image
debezium/debezium pull request #2555
Opened 2021-07-24 21:24 UTC by novotnyJiri

https://issues.redhat.com/browse/DBZ-3650

2021-07-25 12:16 UTC, jcechace requested changes

2021-07-25 12:16 UTC, jcechace commented on jenkins-jobs/job-dsl/downstream_rhel_prepare.groovy
> +pipelineJob('downstream-rhel-prepare-prepare-job') {
use ``rhel-downstram-prepare-job`` and name the fille ``rhel_downstream_prepare.groovy``

2021-07-27 06:37 UTC, jpechane commented on jenkins-jobs/job-dsl/downstream_rhel_prepare.groovy
> +        textParam('DBZ_CONNECTOR_ARCHIVE_URLS', "", "List of URLs to productised Debezium connectors")
PLease be consistent in using single quotes to denote empty string

2021-07-27 06:38 UTC, jpechane commented on jenkins-jobs/job-dsl/downstream_rhel_prepare.groovy
> +        textParam('DBZ_EXTRA_LIBS', "", "List of extra libraries added to connectors")
See above

2021-07-27 06:44 UTC, jpechane approved these changes
@novotnyJiri LGTM, I've left just minor comments related to string quotes usage. When corrected and Jakub's comments are incorporated then we are good to go.

2021-08-04 07:33 UTC, merged

2021-08-04 07:34 UTC, jpechane commented
@novotnyJiri Applied, thanks!