DBZ-3577 Fix empty high watermark check
debezium/debezium pull request #2653
Opened 2021-08-29 03:56 UTC by kgalieva

Check heartbeat reaching low watermark in case the high watermark is empty(no binlog events between watermarks)

2021-08-30 07:53 UTC, gunnarmorling commented
@jpechane, this one is for you :)

2021-08-30 07:53 UTC, gunnarmorling commented
Thanks @kgalieva, we'll take a look asap.

2021-08-31 04:20 UTC, jpechane requested changes
@kgalieva Hi, thanks a lot. Could you please create a separate Jira issue describing the problem and change the commit message to link to it? The Jiras should not be reused across the releases.

I've added a small request for change.

Also is the sitation this PR is fixing something that can be reproduced? If yes, then could you please add a test?

2021-08-31 04:20 UTC, jpechane commented on debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotContext.java
> +        if (highWatermark.getUUIDSets().isEmpty()) {
Could you please restructure the code use use `return x ? y : z`?

2021-09-06 08:53 UTC, merged

2021-09-06 08:53 UTC, jpechane commented
@kgalieva Applied, thanks!