DBZ - 4558 Create trigger job for connector jobs
debezium/debezium pull request #3203
Opened 2022-02-07 10:51 UTC by MartinMedek

2022-02-07 13:16 UTC, jcechace requested changes

2022-02-07 13:16 UTC, jcechace commented on jenkins-jobs/pipelines/connector_tests_trigger_pipeline.groovy
> +                        label = "#" + build.getNumber() + " " + branch
``label = "#${build.number}} ${branch}" `` should work -- use Groovy String tamplates

2022-02-08 17:20 UTC, gunnarmorling commented
@jcechace, @MartinMedek, is this one good to go now?

2022-02-10 11:34 UTC, MartinMedek commented
https://issues.redhat.com/browse/DBZ-4558

2022-02-10 11:34 UTC, jcechace approved these changes

2022-02-10 11:34 UTC, merged