DBZ-5123: Interpret data-collections signal as regex for ad-hoc snapshotting
debezium/debezium pull request #3493
Opened 2022-05-12 21:40 UTC by Chrisss93

This is a quick  attempt at redefining the data-collections-ids of a Debezium signal for ad-hoc snapshot to be a comma-separated list of regular expressions (similar to the`table.include.list` configuration parameter) instead of a comma-separated list of fully-qualified-names. Since this ad-hoc snapshotting signal and the `table.include.list` property appear to be complements, there seems to be value, at least to me, in bringing these concepts closer together by allowing them to be defined and interpreted in the same way. 

A few consequences of this:
1. the ad-hoc snapshotting no longer accepts _quoted_ fully-qualified-names (the `IncrementalSnapshotIT` class in the debezium-mysql-connector relied on this). Quoted fully-qualified-names do not work on the `table.include.list` property anyways.
2. While in most cases, users can continue to use the `data-collections` field for ad-hoc snapshotting as if it were still a fully-qualified name, this change might break existing behaviour for tables whose names are invalid regex (ie. a mysql table can be called `(` or a postgres table called `foo(`). In these cases, the offending regex characters must be escaped.

I'll add some stuff to the relevant docs in the MR once someone has given it a look over and tells me if I'm on the right track.

2022-05-13 10:48 UTC, jpechane commented
@Chrisss93 Thanks for the PR. It is ddefinitely good start. We cannot get rid of quote support due to https://issues.redhat.com/browse/DBZ-4244hat also means that MySQL test database name should stay as is to verify exactly this scenario. So it is necesary to either keep the support or provide a very simple substitute for it.

2022-05-13 10:48 UTC, jpechane commented
@Chrisss93 Thanks for the PR. It is ddefinitely good start. We cannot get rid of quote support due to https://issues.redhat.com/browse/DBZ-4244hat also means that MySQL test database name should stay as is to verify exactly this scenario. So it is necesary to either keep the support or provide a very simple substitute for it.

2022-05-16 16:48 UTC, Chrisss93 commented
> @Chrisss93 Thanks for the PR. It is ddefinitely good start. We cannot get rid of quote support due to https://issues.redhat.com/browse/DBZ-4244 That also means that MySQL test database name should stay as is to verify exactly this scenario. So it is necesary to either keep the support or provide a very simple substitute for it.

Thanks for the advice @jpechane , I've restored the test-case where database names may contain dashes and showed how one can still target that database with an ad-hoc snapshot signal in the new regex-based data-collections.

2022-05-17 08:17 UTC, jpechane commented
@Chrisss93 LGTM, could you please rebase the PR against the latest main and undraft it? Thanks

2022-05-18 12:36 UTC, jpechane commented
@Chrisss93 Tests are filing locally too - try `IncrementalSnapshotIT`. Could you please take a look at it?

2022-05-19 07:00 UTC, jpechane requested changes
Waiting for tests to pass

2022-05-19 14:38 UTC, Naros commented
So the issue here is with the changes made to MySQL's `IncrementalSnapshotIT` with the rework of the return values for the various methods.  The tests are no longer getting the same expected table names in the right formats and that is creating the test failures.  @jpechane is there a specific reason why MySQL required the use of the double-quoted table name format?

2022-05-19 14:55 UTC, Naros commented
Test failures fixed; @Chrisss93 please take a look at my changes and let me know if you see any issues with what I changed.

2022-05-19 16:13 UTC, chrisVia commented
> Test failures fixed; @Chrisss93 please take a look at my changes and let me know if you see any issues with what I changed.

Changes look good to me - at the end of the day this is more about a bit of mysql-connector test quirkiness than the functional behaviour of this ticket. Sorry for the failures, I was using the -nsu flag with Maven so I didn't catch all of them locally after some iterations.

2022-05-19 17:00 UTC, Naros commented
No worries at all, I'll let @jpechane give this one additional pass from his perspective since I know he wanted to merge this before my stop signal work.  @jpechane regarding the stop-signal PR #3492, once this is merged I'll rebase and reverify.  There is a few refactor changes I can make in my PR that tidy up both my work with the work done here.

2022-05-19 21:02 UTC, Naros commented
@Chrisss93 would you mind giving this PR a rebase against `main` if you have moment before the weekend?

2022-05-24 10:46 UTC, merged

2022-05-24 10:46 UTC, jpechane commented
@Chrisss93 @Naros Applied, thanks guys!

2022-05-24 16:10 UTC, Chrisss93 commented
@jpechane Apologies, I could not locally reproduce the SQLServer connector test failures.