DBZ-5069 Upgarde maven-core & maven-plugin-api to 3.8.4
debezium/debezium pull request #3607
Opened 2022-06-13 10:39 UTC by ani-sha

https://issues.redhat.com/browse/DBZ-5069

2022-06-13 11:08 UTC, jpechane requested changes

2022-06-13 11:08 UTC, jpechane commented on debezium-schema-generator/pom.xml
> +      <version>[3.8.4]</version>
I don't think the brackets should be used here. Also as was mentioned in the Jira comment, could you please introduce a new property like `maven.version` that would be used by the enforcer plugin and scheme generator dependencies so it set in a single place?

2022-06-15 07:28 UTC, ani-sha commented
Db2 failure tracked via https://issues.redhat.com/browse/DBZ-5252

2022-06-15 12:42 UTC, merged

2022-06-15 12:43 UTC, jpechane commented
@ani-sha Applied, thanks