DBZ-5267 Invalid date 'SEPTEMBER 31'
debezium/debezium pull request #3623
Opened 2022-06-17 14:21 UTC by harveyyue

https://issues.redhat.com/browse/DBZ-5267

2022-06-20 06:53 UTC, jpechane commented
@harveyyue Hi, thanks for the report. Could you please take a look at https://debezium.io/documentation/reference/1.9/connectors/mysql.html#mysql-property-event-deserialization-failure-handling-mode and make it compatible/driven by the same config option?

Also does this cover situation when an invalid date is defined as default value?

2022-06-20 07:00 UTC, jpechane requested changes
@harveyyue I've left one comment

2022-06-20 15:41 UTC, harveyyue commented
> @harveyyue I've left one comment

@jpechane Ok, I will look into your comments.

2022-06-23 02:17 UTC, harveyyue commented
@jpechane Done with these review

2022-06-23 09:54 UTC, harveyyue commented on debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java
> +                                                String columnType, String exception, Serializable defaultValue) {
Done.

2022-06-24 11:12 UTC, jpechane approved these changes
@harveyyue That's exactly what we need! Would it be possible to add a test for this too? I am not sure if our test database setup will allow to. If not we will merge it as is.

2022-06-24 13:43 UTC, harveyyue commented
> @harveyyue That's exactly what we need! Would it be possible to add a test for this too? I am not sure if our test database setup will allow to. If not we will merge it as is.

If execute following statement in streaming phase, can verify these code changes, but the invalid data in binlog could be read by other IT tests if SnapshotMode is NEVER. So I suggest that don't add the IT test.

`set sql_mode='ALLOW_INVALID_DATES';
insert into DBZ5267(d1, c1) values('2022-09-31', '2022-09-31 09:00:00');`

2022-06-24 14:27 UTC, merged