DBZ-5035 pass sink config props to db history adapter
debezium/debezium pull request #3626
Opened 2022-06-19 16:30 UTC by zalmane

2022-06-20 08:31 UTC, jpechane requested changes

2022-06-20 08:58 UTC, zalmane commented on debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
> +        Configuration dbHistoryConfig = config.filter(k -> k.startsWith(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING) || k.startsWith("debezium.sink."))
will this be OK in terms of dependencies when packaging this outside of Debezium server?

2022-06-20 10:53 UTC, jpechane commented on debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
> +        Configuration dbHistoryConfig = config.filter(k -> k.startsWith(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING) || k.startsWith("debezium.sink."))
Damn you are right. Unfortunately the fix will not be that easy then as server refs (even indirect) should not leak into the core.

2022-06-20 11:37 UTC, zalmane commented
do you mean regarding referencing the variable or in general? I can add a
constant at the class level.
another option is to pass the entire config to the history adapter instead
of limiting it to the history related settings.
WDYT?

On Mon, Jun 20, 2022, 13:54 Jiri Pechanec ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
> <https://github.com/debezium/debezium/pull/3626#discussion_r901532081>:
>
> > @@ -101,7 +101,7 @@ public DatabaseHistory getDatabaseHistory() {
>          }
>
>          // Do not remove the prefix from the subset of config properties ...
> -        Configuration dbHistoryConfig = config.subset(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING, false)
> +        Configuration dbHistoryConfig = config.filter(k -> k.startsWith(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING) || k.startsWith("debezium.sink."))
>
> Damn you are right. Unfortunately the fix will not be that easy then as
> server refs (even indirect) should not leak into the core.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/debezium/debezium/pull/3626#discussion_r901532081>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANAS5XAVDTL4UKEHXHGLZTVQBEUTANCNFSM5ZGTXVMQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-21 08:42 UTC, zalmane commented on debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
> +        Configuration dbHistoryConfig = config.filter(k -> k.startsWith(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING) || k.startsWith("debezium.sink."))
do you mean regarding referencing the variable or in general? I can add another local
constant at the class level.
Another option is to pass the entire config to the history adapter instead
of limiting it to the history related settings, which may be useful for other purposes.
WDYT?

2022-07-13 13:29 UTC, jpechane commented on debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
> +        Configuration dbHistoryConfig = config.filter(k -> k.startsWith(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING) || k.startsWith("debezium.sink."))
@zalmane Could you please take a look at this one so we can wrap it up? Thanks

2022-08-12 11:36 UTC, ggaborg commented on debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
> +        Configuration dbHistoryConfig = config.filter(k -> k.startsWith(DatabaseHistory.CONFIGURATION_FIELD_PREFIX_STRING) || k.startsWith("debezium.sink."))
Hi, check out this new pull request as per your recommendations: https://github.com/debezium/debezium/pull/3797

2022-08-16 15:03 UTC, jpechane commented
Implemented via https://github.com/debezium/debezium/pull/3797

2022-08-16 15:03 UTC, closed without merging