DBZ-5290 Upgrade SQL Server driver to 10.2.1.jre8
debezium/debezium pull request #3639
Opened 2022-06-22 16:20 UTC by Naros

https://issues.redhat.com/browse/DBZ-5290

- [x] Update documentation
- [x] Update `deebzium-examples` repository to explicitly disable encryption. 
https://github.com/debezium/debezium-examples/pull/267

2022-06-23 05:50 UTC, jpechane commented
@Naros Looking at the errors, is it possible it uses SSL by default now?

2022-06-23 12:41 UTC, Naros commented
Hi @jpechane it does.  It looks like in 10.2, quite a lot of breaking changes:
https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16#changes-in-102

Specifically to this problem, `encrypt` is enabled by default whereas in 9.4 it was not.  Should we hold off on this upgrade then or what other changes do you suggest we do to align with the latest?

2022-06-24 10:43 UTC, jpechane commented
I think we should bite a bullt and get this resolved, yet I don't see it as a priority so somebody else but you could take a look.

2022-07-23 18:18 UTC, Naros commented
So @jpechane, I simply explicitly disabled the encryption for our test suite.  

According to this link:
https://techcommunity.microsoft.com/t5/azure-database-support-blog/pkix-path-building-failed-unable-to-find-valid-certification/ba-p/2591304

We will need to download and import the TLS1 and TLS2 certifications using `keytool` and this would need to be done on the host that runs the build as I'm not sure we necessarily wanted to do this, I opted for using the `encrypt=false` on the connection URL for the test suite for now.  Let me know if you would rather we take a different approach.

2022-07-29 03:34 UTC, Naros commented
@vjuranek since Jiri is on PTO, do you have any preference or opinion on this PR?

2022-07-29 07:47 UTC, vjuranek commented
I'm completely fine with disabling encryption in the testsuite, but given that this is the default JDBC drive setting, won't it break user deployments after upgrade?

2022-07-29 12:51 UTC, Naros commented
It would be an incompatibility that would require connector reconfiguration by adding `database.encrypt=false` if they don't use encryption but with the volume of SQL Server users with issues with TLSv1 being unavailable and requiring legacy cyphers, I'm wondering whether having the latest driver would help rather than one that is older, idk.

2022-08-05 16:46 UTC, Naros commented
So here's a thought to maintain backward compatibility.

In prior versions, if you wanted to support encryption, `database.encrypt` and all the driver bits had to be provided by the user.  If the encrpyt option wasn't provided, encryption wasn't enabled.  

To remain backward compatible, how about we check whether `database.encrypt` is even provided by the user configuration.  If it is, we simply pass that through without making any changes.  If we find the user does not supply `database.encrypt`, we inject this configuration with a value of `false`, simulating the old driver behavior as the default.

@vjuranek @jpechane what's your thoughts?

2022-08-05 19:51 UTC, vjuranek commented
Sounds good to me @Naros . Actually I'm fine with both options (breaking backward compatibility as well as keeping it) - as this is for 2.0 it's fine to break backward compatibility. I was just little bit worried that it may affect quite a lot of users (from my experience, lots of users don't read release notes, upgrade manuals etc.). Of course this comes with costs developing code for keeping it backward compatible and maintaining it. I'm too short with Debezium to have any relevant opinion on it (especially not knowing the user community well enough, have no idea how many users will actually be affected etc.). So completely up to you @Naros and @jpechane .

2022-08-08 15:10 UTC, jpechane commented
@Naros @vjuranek I'd vote for breaking backward compatibility. But how difficult would be then for a new user to start with Debezium? If too many steps are required then let's follow the path of adding {{database.encrypt=false}} by default as the user can always override it.

2022-08-08 16:02 UTC, Naros commented
In order to use encryption with the docker container, it would appear we need to follow these steps:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-security?view=sql-server-ver16

This basically involves:
- Creating `.key` and `.pem` files
- Supplying a custom `mssql.conf` file that needs to be mounted
- Start `mssql/server` and mount the `.key`, `.pem`, and `.conf` files into the container

I think in order to simplify using Debezium + SQL Server in both the main repository as well as in the examples repository, we may want to think about creating a pre-built container with these files mounted in the right locations so that we don't need to worry about adding all the mount details in multiple places.  Then we document that if you don't use encryption, the user would need to explicitly provide `database.encrypt=false` in their connector details.

2022-08-09 08:03 UTC, vjuranek commented
> **UPDATE** Actually, I think what might work is we mount the files as part of the test suite in the main repository and then we use the toggle to disable encryption for the tutorial as that would give us a way to test both scenarios and avoids a complicated set up on the tutorial and avoids the creation of a new container, wdyt?

sounds good to me

2022-08-09 09:45 UTC, jpechane commented
@Naros :+1:  on the proposal

2022-08-09 19:54 UTC, Naros commented
Added PR https://github.com/debezium/debezium-examples/pull/267 to address the examples repository.  The examples PR can be merged without this PR since `database.encrypt=false` is the default behavior with the current driver but will be necessary when the driver update is merged in this repository.

2022-08-09 20:15 UTC, roldanbob requested changes

2022-08-09 20:15 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +The Microsoft JDBC SQL server uses SSL encrypted connections by default.
```suggestion
By default, JDBC connections to Microsoft SQL Server are protected by SSL encryption.
```

2022-08-09 20:15 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +If the SQL Server database does not have SSL enabled, or you wish to connect without using SSL, please specify the `database.encrypt=false` option in the connector configuration to disable SSL suppor
```suggestion
If SSL is not enabled for a SQL Server database, or if you want to connect to the database without using SSL, you can disable SSL by setting the value of  the `database.encrypt` property in connector configuration to `false`.
```

2022-08-09 20:15 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|The SSL truststore where the server certificates are stored. This is required when `database.encrypt=false` is not specified.
```suggestion
|The path to the SSL truststore that stores the server's signer certificates. 
This property is required unless database encryption is disabled (`database.encrypt=false`).
```

2022-08-09 20:15 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|The SSL truststore password. This is required when `database.encrypt=false` is not specified.
```suggestion
|The SSL truststore password. 
This property is required unless database encryption is disabled (`database.encrypt=false`).
```

2022-08-09 20:15 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +<13> The SSL truststore password. This is required when `database.encrypt=false` is not specified.
```suggestion
<12> The path to the SSL truststore that stores the server's signer certificates. 
This property is required unless database encryption is disabled (`database.encrypt=false`).
<13> The SSL truststore password. 
This property is required unless database encryption is disabled (`database.encrypt=false`).
```

2022-08-10 18:44 UTC, Naros commented
I have been looking at the random SQL Server test failures and they don't seem to be related to the driver change.  I've been able to reproduce the failure with `testTableExcludeList` only once and even then I wasn't able to get much detail and haven't been able to reproduce it since.  The other also appears to be random as it passes locally.

2022-08-11 11:28 UTC, merged

2022-08-11 11:28 UTC, jpechane commented
@Naros Good solution, thanks!