DBZ-3007: limit 'Streaming requested from LSN' logging
debezium/debezium pull request #3831
Opened 2022-08-29 09:35 UTC by winklerm

https://issues.redhat.com/browse/DBZ-3007

Introduced the "rate limit" for logging this particular log message at most once in 10 seconds.

2022-08-29 09:37 UTC, winklerm commented on debezium-core/src/main/java/io/debezium/util/TimeBasedRateLimiter.java
> +@NotThreadSafe
The class is not designed to be thread safe - if the `AbstractMessageDecoder` needs thread safety of this class, please let me know.

2022-08-29 14:35 UTC, Naros requested changes
Hi @winklerm take a look at `RelationalSnapshotChangeEventSource`, there is a method in that class called `getTableScanLogTimer`.  In effect, the new class you've introduced already exists as a `Timer` implementation.  You should be able to use the snapshot event source as a guide for how to make the change in the decoder without the new class implementation.

2022-08-30 11:34 UTC, winklerm commented
Hi @Naros thanks for the hint, will take a look!

2022-08-30 21:49 UTC, winklerm commented
@Naros Hi, I have updated the PR with your suggested changes. Please take a look, thanks!

2022-08-31 14:30 UTC, Naros approved these changes
LGTM @winklerm, if CI passes I'll merge.

2022-08-31 15:45 UTC, merged