DBZ-5621 Mysql connector can't parse alter database statement including specified comment
debezium/debezium pull request #3891
Opened 2022-09-19 09:31 UTC by harveyyue

https://issues.redhat.com/browse/DBZ-5621

2022-09-19 12:13 UTC, jpechane requested changes
The DDL is invalid and server will not accept it. We need first to understand how it got into binlog before changing the grammar.

2022-09-19 13:36 UTC, harveyyue commented
> The DDL is invalid and server will not accept it. We need first to understand how it got into binlog before changing the grammar.

@jpechane I left a comment in [DBZ-5621](https://issues.redhat.com/browse/DBZ-5621), please help to check.

2026-01-06 14:00 UTC, Naros commented
:x: Developer Certificate of Origin (DCO) check failed.

Hi @harveyyue, please sign off all commits with:

```
git commit -s
```

If pull request commits are not signed off, the pull request cannot be merged. For more information about why this is required, please see [our blog](https://debezium.io/blog/2025/12/12/contribution-requirements-changing/) about contribution requirement changes.

2026-08-04 01:13 UTC, Naros commented
Thank you for your contribution.

This pull request is being closed due to extended inactivity. If you would like to continue working on this, please feel free to reopen this pull request or submit a new one against the latest main branch. We appreciate your interest in improving Debezium.

2026-08-04 01:13 UTC, closed without merging