DBZ-5792: Fix for - Message with LSN XYZ not present among LSNs seen …
debezium/debezium pull request #4033
Opened 2022-11-07 07:37 UTC by rajdangwal

…in the location phase

2022-11-08 11:32 UTC, jpechane commented
@rajdangwal Warning, I've rebased on the latest main and force-pushed to bypass the CI Postgres test failure

2022-11-08 12:14 UTC, jpechane commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
> +                case TRUNCATE:
Plese check pgoutput CI results. The `TRUNCATE` message is supported by Debezium.

2022-11-08 12:15 UTC, jpechane requested changes
Please check pgoutput CI results. The `TRUNCATE` message is supported by Debezium.

2022-11-09 06:09 UTC, rajdangwal commented
Thanks @jpechane for taking care of the build.
The required tests are passing now.

2022-11-09 07:28 UTC, merged

2022-11-09 07:28 UTC, jpechane commented
@rajdangwal Applied, thanks!