DBZ-5924 respect SQL-Server database.instance config option
debezium/debezium pull request #4130
Opened 2022-12-10 16:31 UTC by keriharris

This change enables the SQL Server connector database.instance config option to be respected.

A couple of comments about the code change:

* the `JdbcConfiguration` config has been passed into `createUrlPattern()` so that we can *optionally* include a port argument in the JDBC URL when using a named instance. This change makes it possible to use named instances with or without ports specified in the config file.

* testing method testConnectionWithOptionRecompile() has been modified to call:

```
    public SqlServerConnection(JdbcConfiguration config, SqlServerValueConverters valueConverters,
                               Set<Envelope.Operation> skippedOperations, boolean useSingleDatabase,
                               String instanceName, boolean optionRecompile) {
```

Prior to this commit it called the other variant of `SqlServerConnection()` - the one without the `optionRecompile` parameter. This PR adapts the call to do what it claims to do - test the connection with `optionRecompile`.

The following provides an overview of the available host/instance/port connection strategies:

* connect using hostname + instance; do not specify port

```
{
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "example.com",
    "database.instance": "my_instance",
    "database.names": "my_database",
    ...
}

kafka-connect       | [2022-12-10 16:01:06,477] TRACE URL: jdbc:sqlserver://example.com\my_instance;databaseName=my_database (io.debezium.jdbc.JdbcConnection:231)
```

* connect using hostname + instance; also specify port

```
{
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "example.com",
    "database.instance": "my_instance",
    "database.port": "11433",
    "database.names": "my_database",
    ...
}

kafka-connect       | [2022-12-10 16:02:59,232] TRACE URL: jdbc:sqlserver://example.com\my_instance:11433;databaseName=my_database (io.debezium.jdbc.JdbcConnection:231)
```

* connect using hostname + port

```
{
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "example.com",
    "database.port": "11433",
    "database.names": "my_database",
    ...
}

kafka-connect       | [2022-12-10 16:04:20,666] TRACE URL: jdbc:sqlserver://example.com:11433;databaseName=my_database (io.debezium.jdbc.JdbcConnection:231)
```

* connect using hostname; no port specified - falls back to default port

```
{
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "example.com",
    "database.names": "my_database",
    ...
}

kafka-connect       | [2022-12-10 16:05:34,992] TRACE URL: jdbc:sqlserver://example.com:1433;databaseName=my_database (io.debezium.jdbc.JdbcConnection:231)
```

2022-12-12 14:02 UTC, jpechane requested changes
@keriharris Overall, LGTM, thanks. I left one comment related code refactoring. There is one queston though. Would it be possible to add a test for named instance case?

2022-12-13 18:55 UTC, keriharris commented on debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
>          dataConnection = new SqlServerConnection(connectorConfig.getJdbcConfig(), valueConverters,
I've pushed a commit to create a `SqlServerJdbcConfiguration` class which extends `JdbcConfiguration`. The instance name is populated in `SqlServerJdbcConfiguration` whenever `SqlServerConnectorConfig.getJdbcConfig()` is called.

2022-12-13 19:07 UTC, keriharris commented
> @keriharris Overall, LGTM, thanks. I left one comment related code refactoring. There is one queston though. Would it be possible to add a test for named instance case?

A named instance test would be hard since docker images of SQL Server don't support named instances [1]. However we could check the JDBC connection strings match our expectations by:

1. create static variants of `SqlServerConnection.connectionString()` to get the URL pattern:

```java
    public static String connectionString(SqlServerJdbcConfiguration config, boolean useSingleDatabase) {
        return connectionString(createUrlPattern(config, useSingleDatabase), config);
    }
```

2. create a static variant of `JdbcConnection.connectionString()` to get the URL string:

```java
    public static String connectionString(String urlPattern, JdbcConfiguration config) {
        Properties props = config.asProperties();
        return findAndReplace(urlPattern, props, JdbcConfiguration.DATABASE, JdbcConfiguration.HOSTNAME, JdbcConfiguration.PORT,
                JdbcConfiguration.USER, JdbcConfiguration.PASSWORD);
    }
```

3. create unit tests that build up the connection URL based on various connection parameters. e.g:

```
    @Test
    public void hostnameAndInstanceConnectionUrl() {
        final SqlServerConnectorConfig connectorConfig = new SqlServerConnectorConfig(
                defaultConfig()
                        .with(SqlServerConnectorConfig.HOSTNAME, "example.com")
                        .with(SqlServerConnectorConfig.INSTANCE, "instance")
                        .build());
        SqlServerJdbcConfiguration jdbcConfig = connectorConfig.getJdbcConfig();
        String urlPattern = SqlServerConnection.connectionString(jdbcConfig, false);
        String url = JdbcConnection.connectionString(urlPattern, jdbcConfig);
        assertEquals(url, "jdbc:sqlserver://example.com\\instance");
    }
```

What do you think?

[1] https://github.com/microsoft/mssql-docker/issues/515

2022-12-14 11:34 UTC, jpechane commented
@keriharris This sounds like a good approach. Would it be possible simplify it a bit just by testing `createUrlPattern` method?

* the method would be change to either protected or default so it is clear they are not to be used by default externally
* mark it with `io.debezium.annotation.VisibleForTesting` annotation
WDYT?

2022-12-15 10:41 UTC, merged

2022-12-15 10:42 UTC, jpechane commented
@keriharris Nice work, applied!