DBZ-5878: Update the Debezium UI Documentation page to include the latest additional steps and UI screenshots
debezium/debezium pull request #4140
Opened 2022-12-15 09:35 UTC by indraraj

Closes https://issues.redhat.com/browse/DBZ-5878
Included the description of **Transformations**, **Topic creation** and **Custome properties** additional steps.
Updated the old Debezium UI screenshots.

2023-01-05 07:17 UTC, jpechane commented
@rk3rn3r @roldanbob Could one of you take a look please? Thanks

2023-01-05 15:13 UTC, roldanbob requested changes
Generally, to avoid confusion about who should perform a task, try to address "the user" directly as "you" rather than in the third person. 
When referring to a UI label, always use bold text vs. quotation marks. Also, avoid the construction "click the <button-label> button". Just say, click <button-label>.

2023-01-05 15:13 UTC, roldanbob commented on documentation/modules/ROOT/pages/operations/debezium-ui.adoc
> +* *Topic creation* - define automatic topic creation default properties and groups.
```suggestion
* *Topic creation* - Define default properties and groups for enabling automatic topic creation.
```

2023-01-05 15:13 UTC, roldanbob commented on documentation/modules/ROOT/pages/operations/debezium-ui.adoc
> +* *Custom properties* - enable pass-thru of additional properties that are not covered by the previous sections can be entered here e.g database.* and database.history.* options. The user can enter a
```suggestion
* *Custom properties* - Enable pass-through of additional properties that are not specified in the previous sections, such as `database.*` and `database.history.*` options. You can enter any valid property name and value.
```

2023-01-17 12:33 UTC, merged

2023-01-17 12:33 UTC, jpechane commented
@indraraj @roldanbob Applied, thanks!

2023-01-17 12:38 UTC, indraraj commented on documentation/modules/ROOT/pages/operations/debezium-ui.adoc
>  * The kebab menu at the right of each connector row provides actions which allow the user to *Pause, Resume, Restart or Delete* the connector.
updated