DBZ-6187 Reading column metadata for each table only once
debezium/debezium pull request #4341
Opened 2023-03-06 23:02 UTC by vivek-chopra

DBZ-6187 Reading column metadata for each table only once in case of multi schema setup when an inclusion list for tables is configured.

WHAT : Support for multi schema table setups where schemaNamePattern is null for the table inclusion list defined in the properties to narrow down the column retrieval from so many schemas for the same table to rather fetch the column metadata only once for multi schema databases.

WHY : Reduce engine startup -> Ready to listen/stream to a greater extent for DBs with multiple schemas setup. Rather than looping over all schemas for the same table, just to fetch table metadata once.

2023-03-07 13:08 UTC, jpechane commented
@vivek-chopra Hi, thanks for the PR. Unfortunately I am really unsure I understand the purpose. What will happen if youhave mutliple schemas with same tables but each table will have a different schema?

2023-03-08 15:19 UTC, vivek-chopra commented
> @vivek-chopra Hi, thanks for the PR. Unfortunately I am really unsure I understand the purpose. What will happen if youhave mutliple schemas with same tables but each table will have a different schema?

@jpechane - Thanks for the comment. Yes, in such a case where different schemas could have different schemas for even same tables then I can think of introducing a new property which would be `false` and not trigger this condition unless a multi schema setup exists with same table definitions. What are your thoughts on the same ?

Why we are proposing this is because with `debezium.engine.table.include.list` property being defined, the engine takes a lot of time iterating so many schemas for the same table scheme which can be reduced to a great extent with this change.

2023-03-09 07:42 UTC, jpechane requested changes
A generic approach to the problem is necessary.

2023-03-10 07:40 UTC, vivek-chopra commented
> @vivek-chopra I understand where you are heading but I am afraid this is not the correct solution. We ae talking about a spcial case here you'd insert into a generic codebase. We need to think and find a different solution that might work for other users and their special needs too.

@jpechane - Yes, I agree. On that front, We were thinking if a new property could be introduced which would mean than this solution is executed only for the specific use cases.

2023-03-13 16:14 UTC, vivek-chopra commented
> > @vivek-chopra I understand where you are heading but I am afraid this is not the correct solution. We ae talking about a spcial case here you'd insert into a generic codebase. We need to think and find a different solution that might work for other users and their special needs too.
> 
> @jpechane - Yes, I agree. On that front, We were thinking if a new property could be introduced which would mean than this solution is executed only for the specific use cases.

@jpechane - Please let us know what are your thoughts on this approach. Accordingly, we could try and plan out as this issue is a major blocker for us due to the slowness it introduces to the engine's start up/run time.

2023-03-14 07:39 UTC, jpechane commented
@vivek-chopra Unfortunately the property does not solve the generic problem, we'd just hard-code a solutioon to a specific deployment.

2026-01-06 13:59 UTC, Naros commented
:x: Developer Certificate of Origin (DCO) check failed.

Hi @vivek-chopra, please sign off all commits with:

```
git commit -s
```

If pull request commits are not signed off, the pull request cannot be merged. For more information about why this is required, please see [our blog](https://debezium.io/blog/2025/12/12/contribution-requirements-changing/) about contribution requirement changes.

2026-08-04 01:15 UTC, Naros commented
Thank you for your contribution.

This pull request is being closed due to extended inactivity. If you would like to continue working on this, please feel free to reopen this pull request or submit a new one against the latest main branch. We appreciate your interest in improving Debezium.

2026-08-04 01:15 UTC, closed without merging