DBZ-6240 Change stream supports filtering schema change event
debezium/debezium pull request #4385
Opened 2023-03-21 12:51 UTC by sunxiaojian

Change stream supports filtering schema change event

2023-03-22 05:27 UTC, jpechane commented
@sunxiaojian Hi, thanks for the PR. I am not fully convinced we want to add such functionality directly to the Debezium internals. Is this something that could be achieve via an SMT? That would be used when needed and be configured to filter out requested DDLs. At the same time it would be applicble at any connector.

2023-03-22 09:25 UTC, sunxiaojian commented
> @sunxiaojian Hi, thanks for the PR. I am not fully convinced we want to add such functionality directly to the Debezium internals. Is this something that could be achieve via an SMT? That would be used when needed and be configured to filter out requested DDLs. At the same time it would be applicble at any connector.

It's ok add an SMT to filter, but I think it should be used with the include.schema.changes configuration

2023-03-22 11:54 UTC, sunxiaojian commented
> We tend to avoid too many config options if possible. Generally only if a performance gain can be obtained which is not the case of DDL filtering.

Okay, I'll add an SMT to filter

2023-05-01 19:01 UTC, Naros reviewed
Overall this LGTM @sunxiaojian, there is just one outstanding task: adding a reference to this new transformation in the documentation.

2023-05-05 02:04 UTC, sunxiaojian commented
> Overall this LGTM @sunxiaojian, there is just one outstanding task: adding a reference to this new transformation in the documentation.

Okay, let me add it

2023-05-05 11:59 UTC, jpechane requested changes
@sunxiaojian Thanks for that. I left two more minor comments to address.

2023-05-05 11:59 UTC, jpechane commented on debezium-core/src/main/java/io/debezium/transforms/SchemaChangeEventFilter.java
> +                    "Support filtering during DDL synchronization!");
```suggestion
                    "Support filtering during DDL synchronization");
```

2023-05-05 11:59 UTC, jpechane commented on debezium-core/src/main/java/io/debezium/transforms/SchemaChangeEventFilter.java
> +        if (includeSchemaChangeEvents == null) {
Please take a look at `io.debezium.transforms.HeaderToValue.HEADERS_FIELD` for better way how to handle field validation.

2023-05-05 11:59 UTC, jpechane commented on debezium-core/src/main/java/io/debezium/transforms/SchemaChangeEventFilter.java
> +        this.includeSchemaChangeEvents = (includeSchemaChangeEvents == null)
IIUC there lines above ensure that `includeSchemaChangeEvents` will be alway non-null.

2023-08-03 10:20 UTC, sunxiaojian commented
@jpechane @Naros PTAL

2023-08-08 10:57 UTC, jpechane requested changes
@sunxiaojian Overall, the code LGTM!
I did few changes in docs. Alos I've one request for you - the name `schema.change.event.include.list` is very confusing as it implies the list of DDL types that should be kept in the stream but IIUC they are in fact removed. So I propose renaming it to either `schema.change.event.exclude.list` or `schema.change.event.filter.list`.

@roldanbob Could you please review the docs as well? I am unsure about the formatting a bit.

2023-08-08 11:59 UTC, sunxiaojian commented
> @sunxiaojian Overall, the code LGTM! I did few changes in docs. Alos I've one request for you - the name `schema.change.event.include.list` is very confusing as it implies the list of DDL types that should be kept in the stream but IIUC they are in fact removed. So I propose renaming it to either `schema.change.event.exclude.list` or `schema.change.event.filter.list`.
> 
> @roldanbob Could you please review the docs as well? I am unsure about the formatting a bit.

@jpechane   Okay , I have modified it to 'schema.change.event.exclude.list'

2023-08-08 16:00 UTC, roldanbob commented
> @roldanbob Could you please review the docs as well? I am unsure about the formatting a bit.

@jpechane Should I approach this as if it's going to be exposed downstream (that is, add the necessary Nebel annotations)?

2023-08-08 23:03 UTC, roldanbob requested changes
@sunxiaojian  Thank you for providing this new documentation. I've suggested some language, style, and formatting changes. 
I tested the formatting changes in a local version of the file, but to guard against the possibility that I missed anything, I'd like to review the changes again after you make updates. 
I've also posted a couple of questions related to fields in the properties table.

Let me know if you have any concerns or questions about any edits.

2023-08-09 10:42 UTC, sunxiaojian commented
> @sunxiaojian Thank you for providing this new documentation. I've suggested some language, style, and formatting changes. I tested the formatting changes in a local version of the file, but to guard against the possibility that I missed anything, I'd like to review the changes again after you make updates. I've also posted a couple of questions related to fields in the properties table.
> 
> Let me know if you have any concerns or questions about any edits.

@roldanbob done

2023-08-09 16:50 UTC, roldanbob requested changes
Added some internal cross-references, removed obsolete formatting, and inserted downstream metadata comments.

2023-08-09 16:50 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/schema-change-event-filter.adoc
> ++
```suggestion
The connector does not send events with the resulting `null` values to Kafka.

The following examples shows a xref:schema-change-event-filter-example-before-processing[schema change event record before it is processed] by the SMT, followed by the xref:schema-change-event-filter-example-after-processing[output after the SMT filters the event].

[[schema-change-event-filter-example-before-processing]]
.Schema change event record before it is processed by the `SchemaChangeEventFilter` transformation
====
```

2023-08-09 16:50 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/schema-change-event-filter.adoc
> +
```suggestion

// Type: reference
```

2023-08-09 16:50 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/schema-change-event-filter.adoc
> +.Schema change event record after processing by the SMT
```suggestion

Based on the earlier xref:example-configuration-schema-change-event-filter[configuration example], after the SMT processes the xref:schema-change-event-filter-example-before-processing[original schema change event], it resets the values for the `DROP` event to `null`, as shown in the following example:

[[schema-change-event-filter-example-after-processing]]
.Schema change event record after processing by the SMT
```

2023-08-10 05:04 UTC, merged

2023-08-10 05:04 UTC, jpechane commented
@sunxiaojian Applied, thanks!