make it support temporal slot
debezium/debezium pull request #4495
Opened 2023-04-25 14:03 UTC by TDtianzhenjiu

1. After specifying the parameter dropSlotOnClose should create a temporal slot in PG
2. After reconnecting, the startStreamingLsn in WalPosition Locator changed, it won't get subsequent changes
So, after getting the position, just keep the same connection

2023-04-28 13:07 UTC, jpechane commented
@TDtianzhenjiu Hi, is there a Jira for this issue? This PR changes the restart behaviour so can we guarantee that we will not end up in-hlaf inconcistent state after connector retry?

2023-05-04 08:40 UTC, TDtianzhenjiu commented
Hello @jpechane 
there's no jira for this issue, but I mailed with @Naros and discussed it with him before

I've tested it in my local env and  I found it won't work with a temporary slot, 
therefore, I debugged the source code and  I found it works if keep the same connection.

2023-05-09 10:34 UTC, jpechane requested changes
@TDtianzhenjiu Thanks for the PR. There are 6 test failures that seems to be related to the change.

2023-05-18 13:58 UTC, TDtianzhenjiu commented
Hello @jpechane 
How can I check these 6 failed tests?
I see the only failed check is: `Commit has no DBZ-xxx prefiix`

2023-05-19 05:10 UTC, jpechane commented
@TDtianzhenjiu Please run the testsuite for `debezium-onnector-postgres` module locally. That should give you enough feedback and at the same time you could use it as the check while you'll be fixing the tests.

2026-01-06 13:59 UTC, Naros commented
:x: Developer Certificate of Origin (DCO) check failed.

Hi @TDtianzhenjiu, please sign off all commits with:

```
git commit -s
```

If pull request commits are not signed off, the pull request cannot be merged. For more information about why this is required, please see [our blog](https://debezium.io/blog/2025/12/12/contribution-requirements-changing/) about contribution requirement changes.

2026-08-04 01:16 UTC, Naros commented
Thank you for your contribution.

This pull request is being closed due to extended inactivity. If you would like to continue working on this, please feel free to reopen this pull request or submit a new one against the latest main branch. We appreciate your interest in improving Debezium.

2026-08-04 01:16 UTC, closed without merging