DBZ-6438 Add config to reset mysql binlog offset
debezium/debezium pull request #4522
Opened 2023-05-05 18:07 UTC by kgalieva

https://issues.redhat.com/browse/DBZ-6438

Allow reseting MySQL connector's offset

### Which use case/requirement will be addressed by the proposed feature?
Add a config to MySQL connector that allows overriding committed offset. Replaying binlog is useful in case of a data corruption incident or data loss incidents. For example an SMT could have an issue in filtering or transformation logic when events get lost or corrupted.

### Implementation
Add an optional config that takes an offset to force reset to. The format is the same as for committed offsets, so that the desired offset could be copied from the connector's offsets topic.
The previous offset gets overridden with the value from config if config is provided.
The schema history will be recovered up to the provided offset, because there could be schema changes between provided and the latest committed offset.

2023-05-06 06:53 UTC, ironakj commented
Hi @kgalieva , even I was working on the same since this is pretty much a very common scenario. Wanted to know, if taken from config, how do you ensure the config is only honored once? i.e. let's say if the connector restarts how would make sure whether to reset position or not

2023-05-06 20:08 UTC, kgalieva commented
Hi @ironakj, great question. The plan is to revert the `force.reset.offset` config soon after the connector starts running and committing the new offsets. An alternative or additional config option could allow retesting only an initial offset, to use it for an existing connector reset one would need to delete committed offsets before restarting a connector.

2023-05-09 05:32 UTC, jpechane requested changes
@kgalieva Thanks for the PR. I must admit I am not really fan of the feature as is at it opens potential can of worms. Also having it public means that we would need to commit to a published offset format which we want to avoid.
But I am willing to compromise on it so we can gather a limited experience/feedback using it.
I proposed in one change to create an internal field out of it. It is an undocumented property then that is not fully supported and will give us quite a leeway. Is it ok for you?

Also one more question - if we'd introduce an offset editor/manipulator, would it be better/mor robust/systematic solution?

2023-05-09 05:32 UTC, jpechane commented on debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/StreamingSourceIT.java
> -            if (mode == null) {
Why is this change necessary? It ensured that the DML was executed in the streaming phase.

2023-05-09 05:32 UTC, jpechane commented on debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
> +    public Document getForceResetOffset() {
Please use `Optional`

2023-05-09 05:32 UTC, jpechane commented on debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
> +    public static final Field FORCE_RESET_OFFSET = Field.create("force.reset.offset")
PLease use `Field.createInternal`

2023-05-09 05:32 UTC, jpechane commented on debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
> +            throw new ConnectException(String.format("Unable to parse the %s config json value %s",
PLease use `DebeziumException`

2023-05-09 14:02 UTC, kgalieva commented
> if we'd introduce an offset editor/manipulator, would it be better/mor robust/systematic solution?

I guess we could stop a connector, commit an offset we want to reset to manually and then restart the connector. I can test it. Is this what you are suggesting by an offset editor/manipulator?

2023-06-05 12:52 UTC, jpechane commented
@kgalieva Yes, that's what I am proposing.

2023-06-05 12:56 UTC, kgalieva commented
I've tried deleting a connector, overriding the offset and  then recreating the connector and it worked. I can close this PR so that upstream can change offset format in the future without worrying about breaking the internal API

2023-06-05 13:12 UTC, jpechane commented
@kgalieva Yes please, we really need to come up with a solution that will be robust, would apply only once and be reusable by all connectors.

2023-06-05 13:13 UTC, closed without merging