DBZ 6408 Add docs on how to extend channels and notification
debezium/debezium pull request #4538
Opened 2023-05-11 09:27 UTC by mfvitale

closes: https://issues.redhat.com/browse/DBZ-6408

2023-05-11 09:28 UTC, mfvitale commented
@roldanbob let me know if you need details on this

2023-05-25 21:44 UTC, roldanbob requested changes
Wow, @mfvitale, you did a ton of work here. Thanks for all of the effort. 

I did a thorough review and did my best to ensure consistency across similar sections. I'm sure that some of my suggestions actually modify pre-existing content, including some that I previously authored, but that I now think should be reworded.  
I might have missed a few things, but after you incorporate suggestions, perhaps I can make another pass to see if anything slipped through the cracks. Thanks.

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +The signal type is `execute-snapshot` and the `data` field must have the following fields:
```suggestion
The signal type is `execute-snapshot`, and the `data` field must have the following fields:
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +| An array of comma-separated regular expressions that match fully-qualified names of tables to be snapshotted. +
```suggestion
| An array of comma-separated regular expressions that match the fully-qualified names of tables to include in the snapshot. +
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-stopping-an-incremental-snapshot-kafka.adoc
> +| The type of the snapshot to be executed. Currently only `incremental` is supported. +
```suggestion
| The type of the snapshot to be executed. 
Currently {prodname} supports only the `incremental` type.  +
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +| The type of the snapshot to be executed. Currently only `incremental` is supported. +
```suggestion
| The type of the snapshot to be executed. 
Currently {prodname} supports only the `incremental` type.  +
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +The format of the names is the same as for xref:#{context}-property-signal-data-collection[signal.data.collection] configuration option.
```suggestion
Specify the names by using the same format as is required for the xref:{context}-property-signal-data-collection[signal.data.collection] configuration option.
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +subset of the contents of the {data-collection}(s).
```suggestion
| An optional string that specifies a condition that the connector evaluates to designate a subset of columns to include in a snapshot.
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +* `additional-condition` is used to select a subset of a {data-collection}'s content.
```suggestion
{prodname} uses the `additional-condition` field to select a subset of a {data-collection}'s content.
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +To snapshot just the content of the `products` {data-collection} where `color=blue`
```suggestion
Typically, when {prodname} runs a snapshot, it runs a SQL query such as:

`SELECT * FROM _<tableName>_ ....`

When the snapshot request includes an `additional-condition`, the `additional-condition` is appended to the SQL query, for example:

`SELECT * FROM _<tableName>_ WHERE _<additional-condition>_ ....`

For example, given a `products` {data-collection} with the columns `id` (primary key), `color`, and `brand`, if you want a snapshot to include only content for which `color=blue`, when you request the snapshot, you could append an `additional-condition` statement to filter the content:
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-kafka.adoc
> +----
```suggestion
----
Key = `test_connector`

Value = `{"type":"execute-snapshot","data": {"data-collections": ["schema1.products"], "type": "INCREMENTAL", "additional-condition":"color=blue"}}`
----

You can use the `additional-condition` statement to pass conditions based on multiple columns.
For example, using the same `products` {data-collection} as in the previous example, if you want a snapshot to include only the content from the `products` {data-collection} for which `color=blue`, and `brand=MyBrand`, you could send the following request:

----
Key = `test_connector`

Value = `{"type":"execute-snapshot","data": {"data-collections": ["schema1.products"], "type": "INCREMENTAL", "additional-condition":"color=blue AND brand=MyBrand"}}`
----
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-nosql.adoc
> +.Procedure using source signaling channel
```suggestion
.Using a source signaling channel to trigger an incremental snapshot
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot-sql.adoc
> +.Procedure using source signaling channel
```suggestion
.Using a source signaling channel to trigger an incremental snapshot
```

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
This file is obsolete and is intended for removal. Although the tag regions in the file correctly render the intended content in the upstream docs, the tag filtering did not work downstream, so I ended up creating separate sql and nosql versions of the incremental snapshots content.

2023-05-25 21:44 UTC, roldanbob commented on documentation/modules/ROOT/partials/modules/all-connectors/proc-triggering-an-incremental-snapshot.adoc
> +.Procedure using source signaling channel
```suggestion
.Using a source signaling channel to trigger an incremental snapshot
```

2023-05-26 01:26 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +NOTE: To use a notification channel with multiple connectors, you must place a copy of the notification channel JAR file in each connector subdirectory.
```suggestion
NOTE: To use a custom notification channel with multiple connectors, you must place a copy of the notification channel JAR file in each connector subdirectory.
```

2023-05-26 09:30 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +* Custom: you can xref:debezium-notification-custom-channel[implement your custom channel] to receive notification from {prodname}.
The out log will be [Notification Service] <notification data>

2023-05-26 10:05 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +// Title: Provide custom signaling channel
Yes it's better. I'll add it.

2023-05-26 10:06 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +A custom converter Java project has compile dependency on the {prodname} Core module.
Yes.

2023-05-26 10:11 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +subset of the contents of the {data-collection}(s).
Here the filters applies on columns with the scope to filter out some rows from data collection table.

2023-05-26 10:13 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +These compile dependencies must be included in your project's `pom.xml`, as shown in the following example:
Yes.

2023-05-26 12:35 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +See the next section for more details.
Removes since it adds nothing.

2023-05-26 12:36 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +To use a signaling channel with a connector, add the converter JAR file to the connector's subdirectory.
Removed.

2023-05-26 16:23 UTC, roldanbob requested changes
@mfvitale Just a few more minor suggestions. I took the liberty of converting the list of tasks for using custom channels into unordered lists and linked each step to the appropriate topic.

2023-05-29 07:43 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +To use signals to trigger a connector to perform a specified action, you can configure the connector use the following channels:
Yes.

2023-05-29 07:45 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +|`{"type":"execute-snapshot","data": {"data-collections": ["public.MyFirstTable"], "type": "INCREMENTAL", "additional-condition":"color=blue AND brand=foo"}}`
Good to know!

2023-05-29 07:47 UTC, mfvitale commented
@roldanbob adresses your suggestions. Do you think we are now in a good point?

2023-05-30 13:11 UTC, roldanbob commented
> @roldanbob your suggestions addressed. Do you think we are now in a good point?

Yes, @mfvitale, I think you're good to go now! Thanks for your patience!

2023-05-30 15:17 UTC, merged

2023-05-30 15:18 UTC, jpechane commented
@mfvitale @roldanbob Applied, thanks!