DBZ-6424 Add docs for new JmxSignalChannel and JmxNotificationChannel
debezium/debezium pull request #4581
Opened 2023-06-07 08:19 UTC by mfvitale

2023-06-07 09:00 UTC, jpechane approved these changes
Technically LGTM, thanks!

2023-06-07 22:08 UTC, roldanbob requested changes
@mfvitale Completed my review. Let me know if you have any questions or if something doesn't look right to you. Thanks!

2023-06-07 22:08 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +
```suggestion
.Procedure
1. Use your preferred JMX client (for example. JConsole or JDK Mission Control) to connect to the MBean server.
2. Search for the Mbean `debezium.__<connector-type>__.management.signals.__<server>__`.
The Mbean exposes `signal` operations that accept the following input parameters:

p0:: The id of the signal.
p1:: The type of the signal, for example, `execute-snapshot`.
p2:: A JSON data field that contains additional information about the specified signal type.
+
Send an `execute-snapshot` signal by providing value for the input parameters. + In the JSON data field, include the information that is listed in the following table:
+
.Execute snapshot data fields
[cols="2,2,6",options="header"]
|===
|Field | Default | Value

|`type`
|`incremental`
| The type of the snapshot to run.
Currently {prodname} supports only the `incremental` type.

|`data-collections`
|_N/A_
| An array of comma-separated regular expressions that match the fully-qualified names of the tables to include in the snapshot. +
Specify the names by using the same format as is required for the xref:{context}-property-signal-data-collection[signal.data.collection] configuration option.

|`additional-condition`
|_N/A_
| An optional string that specifies a condition that the connector evaluates to designate a subset of records to include in a snapshot.
|===
+
The following image shows an example of how to use JConsole to send a signal:
+
```

2023-06-08 08:16 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +The notifications are also exposed as a JMX notification with type `debezium.notification`.
This is not something that you can decide to, notifications are automatically exposed as jmx notifications.

2023-06-08 08:20 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +To use the `sink` notification channel, you must also set the `notification.sink.topic.name` configuration property to the name of the topic where you want {prodname} to send notifications.
Let me review this part.

2023-06-08 09:36 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/notification.adoc
> +To use the `sink` notification channel, you must also set the `notification.sink.topic.name` configuration property to the name of the topic where you want {prodname} to send notifications.
I added a dedicated section as for Kafka signal properties. Also I noticed that the section about Kafka signal was still only for MySQL even if now it is available for all connectors, so I moved it.

2023-06-08 20:08 UTC, roldanbob requested changes
A handful of additional suggestions. After you make your next round of changes, I'll do a local Antora build to see how things look and get a better sense of whether we've missed anything and verify that the formatting is good.

2023-06-08 20:08 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> ++
```suggestion
3. Send an `execute-snapshot` signal by providing value for the input parameters. +
In the JSON data field, include the information that is listed in the following table:
+
```

2023-06-09 14:11 UTC, roldanbob commented
> I think we are ready to merge @roldanbob

Yes, I just checked the rendering, and everything LGTM. Thanks!

2023-06-09 18:10 UTC, merged