DBZ-6592 Documenting database permissions required by the MongoDB connector
debezium/debezium pull request #4660
Opened 2023-07-07 09:37 UTC by jcechace

https://issues.redhat.com/browse/DBZ-6592

2023-07-07 09:38 UTC, jcechace commented
@roldanbob  as usual, please review and suggest of directly commit any changes as you see fit. Thank you!

2023-07-07 16:54 UTC, roldanbob requested changes
Here you go, @jcechace. Let me know if you have any questions.
Thanks!

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +In any case the user should also have the permission to execute the https://www.mongodb.com/docs/manual/reference/command/ping/[ping] command.
```suggestion
.Permission to use the MongoDB `ping` command 

Regardless of the `capture.scope` setting, the user requires permission to run the MongoDB https://www.mongodb.com/docs/manual/reference/command/ping/[ping] command.
```

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +Additionally when capturing changes from a sharded MongoDB cluster and the xref:mongodb-property-mongodb-connection-mode[`mongodb.connection.mode`] property is set to `replica_set` the user used by t
```suggestion
.Permission to read the `config.shards` collection

For connectors that capture changes from a sharded MongoDB cluster, and for which the xref:mongodb-property-mongodb-connection-mode[`mongodb.connection.mode`] property is set to `replica_set`, you must grant the user permission to read the `config.shards` system collection.
```

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +|Specifies the https://www.mongodb.com/docs/manual/changeStreams/#watch-a-collection--database--or-deployment[scope of change streamed] opened by the connector.
```suggestion
|Specifies the https://www.mongodb.com/docs/manual/changeStreams/#watch-a-collection--database--or-deployment[scope of the change streams] that the connector opens.
```

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +`deployment`:: opens a change stream cursor for a deployment (either a replica set or a sharded cluster) to watch for changes to all non-system collections across all databases except for `admin`, `l
```suggestion
`deployment`:: Opens a change stream cursor for a deployment (either a replica set or a sharded cluster) to watch for changes to all non-system collections across all databases, except for `admin`, `local`, and `config`.
```

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +`database`:: opens a change stream cursor for a single database to watch for changes to all its non-system collections.
```suggestion
`database`:: Opens a change stream cursor for a single database to watch for changes to all of its non-system collections.
```

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +To use signaling when `database` is specified as the value the signaling collection needs to be located in the database specified by the xref:mongodb-property-capture-target[`capture.target`] propert
```suggestion
If you set the value of this property to `database`,  to use {prodname} signaling , the signaling collection must reside in the database that is  specified by the xref:mongodb-property-capture-target[`capture.target`] property.
```

2023-07-07 16:54 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +| Specifies the database to watch for changes when xref:mongodb-property-capture-scope[`capture.scope`] is set to `database`
```suggestion
| Specifies the database that the connector monitors for changes.
This property applies only if the xref:mongodb-property-capture-scope[`capture.scope`] is set to `database`.
```

2023-07-07 21:06 UTC, jcechace commented
@roldanbob  Great, this is much better (as is usually the case after your touch). Thank you!

2023-07-09 18:27 UTC, jcechace commented
@roldanbob  reread please and accept the review if this can be merged.

2023-07-10 13:32 UTC, roldanbob requested changes
@jcechace Review complete. Found a couple things that I missed earlier. If you could work in these changes, I think this is now all set. Thanks!

2023-07-10 13:32 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +If you set the value of this property to `database`,  to use {prodname} signaling , the signaling collection must reside in the database that is  specified by the xref:mongodb-property-capture-target
```suggestion
If you set the value of this property to `database`, to use {prodname} signaling, you the signaling collection that you create must reside in the database that is specified by the xref:mongodb-property-capture-target[`capture.target`] property.
```
Removed some extra spaces and slightly reworded.

2023-07-10 16:37 UTC, roldanbob approved these changes
LGTM!

2023-07-11 14:13 UTC, merged