DBZ-6532 S3 schema history config
debezium/debezium pull request #4771
Opened 2023-08-11 09:56 UTC by jpechane

2025-03-26 06:42 UTC, jpechane commented
@kmos Yes, we should. This is also one of my loose ends :-(.

2025-03-26 07:55 UTC, kmos commented
ok! I can take a look

2025-03-28 05:04 UTC, jpechane commented
@kmos Could you pleae rebases instead of merges so PR doesn't contain merge commits to keep linear history? Thanks

2025-03-31 10:52 UTC, kmos commented
Hi @jpechane ,

can you give a look? I have also added the missed storage.

2025-04-03 11:23 UTC, jpechane reviewed
@kmos Thanks for wrapping this up! I left few minor comments.
Other then that the content is fine from technical PoV.

2025-04-03 11:23 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|===
We need to add pass-thorough properties too, for more details for example https://debezium.io/documentation/reference/3.1/connectors/mysql.html#debezium-mysql-pass-through-database-history-properties-for-configuring-producer-and-consumer-clients

2025-04-03 11:23 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|link:https://raw.githubusercontent.com/debezium/debezium/main/debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStoreConfig.java[source code]
I'd prefer a separate section under the options table that would should DDLs instead of links to the source code

2025-04-03 11:23 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|link:https://raw.githubusercontent.com/debezium/debezium/main/debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/history/JdbcSchemaHistoryConfig.java[source code]
I'd prefer a separate section under the options table that would should DDLs instead of links to the source code

2025-04-07 05:52 UTC, jpechane reviewed
@kmos Thanks a lot. I left one more claryfying comment WRT the passthrough properies, other than that we are good to go.
Unfortunately I cannot approve PR I created.
It can be merged  when @roldanbob take a fast peek over it.

2025-04-07 05:52 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|[[schema-history-internal-tbd-security-protocol]]<<schema-history-internal-tbd-security-protocol,`schema.history.internal.*.security.protocol`>>
@kmos I am sorry for being unclear, I intended to have `schema.history.internal.consumer.*` and `schema.history.internal.producer.*` only. There is no need for the finer settings as it will be always subset of Kafka client documentation.

2025-04-14 21:39 UTC, roldanbob requested changes
I've completed a pretty thorough review of everything through L364, with just a few comments beyond there related to the possibility of . I'm going to stop here for today, but I intend to review the balance tomorrow.
Let me know if you have any questions; think that any of my suggestions are way off base; or if you just want further clarification. Thanks.

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|(Optional) Username of the database which will be used to access the database storage.
```suggestion
|(Optional)  The username through which {prodname} connects to the database that stores internal schema history data.
```

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|(Optional) Password of the database which will be used to access the database storage.
```suggestion
|(Optional)  Password for the user specified by xref:jdbc-history-schema-history-user[`schema.history.internal.jdbc.connection.user`].
```

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|(Optional) Delay of retry on wait for connection failure.
```suggestion
|(Optional) Specifies the time, in milliseconds, that the connector waits to retry the connection after an attempt to connect to the internal schema history database fails.
```

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|(Optional) Maximum number of retry attempts before giving up.
```suggestion
|(Optional) Specifies the maximum number of times that {prodname} retries the connection to the internal schema history database after a connection failure.
```

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|The name of the table to which the history will be stored.
```suggestion
|The name of the table where {prodname} store the internal schema history.
```

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|<<jdbc-offset-table-ddl-default, `see table section`>>
```suggestion
|xref:jdbc-offset-table-ddl-default[`jdbc.offset.table.ddl.default` (1. Table Structure)]
```

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `io.debezium.storage.redis.offset.RedisOffsetBackingStore`
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `io.debezium.storage.redis.history.RedisSchemaHistory`
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `io.debezium.storage.s3.history.S3SchemaHistory`.
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `io.debezium.storage.azure.blob.history.AzureBlobSchemaHistory`.
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `io.debezium.storage.rocketmq.history.RocketMqSchemaHistory`.
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `org.apache.kafka.connect.storage.KafkaOffsetBackingStore`.
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Must be set to `io.debezium.storage.file.history.FileSchemaHistory`
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-14 21:39 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
If this and similar properties have required values, can they be coded to carry the appropriate defaults?

2025-04-15 16:53 UTC, kmos commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
Actually I don't know what could be the right default. Maybe the `MemoryOffsetBackingStore` but actually the code doesn't have a default value. WDYT @jpechane?

2025-04-15 16:57 UTC, kmos commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
The [same](https://github.com/debezium/debezium/pull/4771/files#r2045071463) as for the `offset` we actually don't have a default value for `schema.history.internal`. Maybe a correct value could be `MemorySchemaHistory`? WDYK @jpechane

2025-04-15 17:03 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
> I like the idea of links but I don't like to have description/text too long in the table. Maybe I prefer to don't use the brackets

So, originally you had a link that went to the top-level item in the tables, which I changed, so that the links went directly to the named properties, but I did not remove the numbered text, moving it within the parentheses/brackets. When you say you might prefer not to use the brackets, I interpret that to mean one of the following:

- Keep the revised links that directly target the named properties, but use only the property names as the link text, and remove the text in parentheses (1. Table structure, and so forth)?
- Keep the revised links, and use the numbered items as the link text (No parentheses), and do not list the property names?

Or something else?

2025-04-15 18:20 UTC, kmos commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
> Keep the revised links that directly target the named properties, but use only the property names as the link text, and remove the text in parentheses (1. Table structure, and so forth)?

Yes, I like to keep the revised links that directly target the named properties, but I am not sure (and I don't have a strong opinion/idea) for the text (which I prefer without numbered items even if I proposed it :eyes: ).  WDYT?

2025-04-15 22:35 UTC, roldanbob requested changes
@kmos Ok, I think that I've looked at everything now. Gave me a good appreciation for how much work this involved for you! Thanks.
Let me know if you have any further questions. In the JDBC offset tables, where link text included text enclosed in parentheses (e.g., `(Table structure)`), I did not remove that text, because I wasn't certain whether removal of the numbers was the main goal, or whether you prefer that the link text reference only the property names and  remove all of the other text.

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|The number of attempts in a row that no data are returned from RocketMQ before recover.
```suggestion
|Specifies the number of consecutive attempts in which RocketMQ returns no data before recovery completes.

```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|The number of milliseconds to wait while polling for persisted data during recovery.
```suggestion
|Specifies the time, in milliseconds, that {prodname} waits after each poll attempt to recover the history.

```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Specifies the time, in milliseconds, that the connector waits for a response after the Kafka AdminClient submits a request to fetch cluster information.
```suggestion
|Specifies the time, in milliseconds, that the connector waits for a response after the Kafka AdminClient submits a request to fetch cluster information before the request times out.
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Specifies the time, in milliseconds, that the connector waits for a response after the Kafka AdminClient submits a request to create a Kafka history topic.
```suggestion
|Specifies the time, in milliseconds, that the connector waits for a response after the Kafka AdminClient submits a request to create a Kafka history topic before the request times out.
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Timeout for sending messages to RocketMQ.
```suggestion
|Specifies the time, in milliseconds, that {prodname} waits for a write to Rocket MQ to complete before the operation times out.
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +[[jdbc-offset-table-ddl-default]]<<jdbc-offset-table-ddl-default,(Table Structure)>>
```suggestion
[[jdbc-offset-table-ddl-default]]<<jdbc-offset-table-ddl-default, `offset.table.ddl.default `(Table Structure)>>
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +[[jdbc-offset-table-select-default]]<<jdbc-offset-table-select-default,(Select query)>>
```suggestion
[[jdbc-offset-table-select-default]]<<jdbc-offset-table-select-default,`jdbc.offset.table.select.default` (Select query)>>
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +[[jdbc-offset-table-insert-default]]<<jdbc-offset-table-insert-default,(Insert query)>>
```suggestion
[[jdbc-offset-table-insert-default]]<<jdbc-offset-table-insert-default,`jdbc.offset.table.insert.default` (Insert query)>>
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +[[jdbc-offset-table-delete-default]]<<jdbc-offset-table-delete-default,(Delete query)>>
```suggestion
[[jdbc-offset-table-delete-default]]<<jdbc-offset-table-delete-default,`jdbc.offset.table.delete.default` (Delete query)>>
```

2025-04-15 22:35 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
I modified the targets for the remaining links in this table to match the values in the link text. Check that I've targeted the correct property names.

2025-04-17 10:35 UTC, kmos commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +[[jdbc-offset-table-ddl-default]]<<jdbc-offset-table-ddl-default,(Table Structure)>>
ok, sorry maybe I get your confusion `offset.table.ddl.default` are not properties available in debezium,  I used it only to link to the default. 

In order to be on the same page: for example the `offset.storage.jdbc.offset.table.ddl` has default:

```sql
CREATE TABLE %s (
id VARCHAR(36)      NOT NULL,
offset_key          VARCHAR(1255),
offset_val          VARCHAR(1255),
record_insert_ts    TIMESTAMP NOT NULL,
record_insert_seq   INTEGER NOT NULL)
```

This text is too big to be available in the second column of the table (*Default*). So write down as **text** something like `offset.table.ddl.default` or `*.select.default` doesn't have an effect into debezium configuration.

So actually it's ok to me the links between defaults but the text I think can make some confusion. 
![image](https://github.com/user-attachments/assets/8016573d-90bc-41c4-8ad2-00f177f81355)

My initial proposal was like `see table section` which was misleading because there wasn't any table section. Maybe the correct text could be something like:

- `create query` - `select query` and so on.

![image](https://github.com/user-attachments/assets/be515f59-9900-4b0c-98e9-9f5de49444d7)

WDYT @roldanbob ?

2025-04-17 13:34 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +[[jdbc-offset-table-ddl-default]]<<jdbc-offset-table-ddl-default,(Table Structure)>>
Yes, I think that is a reasonable solution, @kmos!

2025-04-22 19:29 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
No, they can't. This is exactly the way how you choose which storage do you use.

2025-04-22 19:30 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +
Again, this is selection to choose the right storage so there can't be sensible default.

2025-04-22 21:21 UTC, roldanbob requested changes
@kmos I found a few minor things. Other than those, I think that you're all set. Thanks for your patience in absorbing my requests and for sticking with it!

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +In addition, connectors such as Db2, MySQL, Oracle,  and SQL Server, require additional storage, the so-called internal schema history, to record their schema evolution history.
```suggestion
In addition, connectors such as Db2, MySQL, Oracle,  and SQL Server, require additional storage for their so-called internal schema history, which records changes to table schema in the database.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +* File offset store for Kafka Connect standalone
```suggestion
[horizontal]
Kafka offset store:: Provides storage for Kafka Connect distributed.
File offset store:: Provides storage for Kafka Connect standalone.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +In all deployments, you use connector properties to configure internal schema history storage.
```suggestion
For connectors that work with schema-based databases, you configure internal schema history storage by setting connector properties.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +You can use the default statements, or you can override the defaults with your own statements to provide compatibility with database dialects or to customize them for specific use cases.
```suggestion
You can use these default statements, or you can override the defaults with your own statements to provide compatibility with database dialects or to customize them for specific use cases.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Specifies the interval, in milliseconds, that {prodname} allows for exchanging offset data with Redis before the socket times out..
```suggestion
|Specifies the interval, in milliseconds, that {prodname} allows for exchanging offset data with Redis before the socket times out.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +|Specifies a time, in milliseconds, that {prodname} waits for confirmation that Redis wrote data to a replica shard before the request times out.
```suggestion
|Specifies the time, in milliseconds, that {prodname} waits for confirmation that Redis wrote data to a replica shard before the request times out.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +{prodname} can use link:https://aws.amazon.com/s3/[Amazon S3] object storage service.
```suggestion
{prodname} can use the link:https://aws.amazon.com/s3/[Amazon S3] object storage service.
```

2025-04-22 21:21 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/storage.adoc
> +Debezium can use the `RocketMqSchemaHistory` class to store and retrieve database schema changes in Apache RocketMQ.
```suggestion
{prodname} can use the `RocketMqSchemaHistory` class to store and retrieve database schema changes in Apache RocketMQ.
```

2025-04-23 13:59 UTC, kmos commented
Thank you for you patience @roldanbob  ! I'll merge it as soon as the release is completed.

2025-04-24 10:55 UTC, jpechane commented
@kmos I think this can be merged.

2025-04-24 11:04 UTC, merged