DBZ-6801 Introduce JDBC sink option `dialect.sqlserver.identity.insert`
debezium/debezium pull request #4783
Opened 2023-08-14 19:28 UTC by Naros

https://issues.redhat.com/browse/DBZ-6801

Documents https://github.com/debezium/debezium-connector-jdbc/pull/27

2023-08-14 20:49 UTC, roldanbob requested changes

2023-08-14 20:49 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/jdbc.adoc
> +|Specifies whether the connector automatically enables identity inserts before an _insert_ or _upsert_ operation and is disabled immediately afterward.
```suggestion
|Specifies whether the connector automatically sets an `IDENTITY_INSERT` before an `INSERT` or `UPSERT` operation into the identity column of SQL Server tables , and then unsets it immediately after the operation.
```

2023-08-14 20:49 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/jdbc.adoc
> +The default is `false`, meaning an insert or upsert into a SQL Server table that has an `IDENTITY` column throws a SQL exception.
```suggestion
When the default setting (`false`) is in effect, an `INSERT` or `UPSERT` operation into the `IDENTITY` column of a table results in a SQL exception.
```

2023-08-14 20:49 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/jdbc.adoc
> +|Specifies whether the connector automatically enables identity inserts before an _insert_ or _upsert_ operation and is disabled immediately afterward.
The convention in the SQL Server documentation seems to be to capitalize SQL commands, so I followed that model.

2023-08-15 12:35 UTC, merged

2023-08-15 12:35 UTC, Naros commented
Applied to main (=2.4)