DBZ-6883 documentation
debezium/debezium pull request #4851
Opened 2023-09-12 08:23 UTC by jcechace

https://issues.redhat.com/browse/DBZ-6883

First commit ought to be applied to both 2.3 and 2.4 
Second commit is exclusive to 2.4

2023-09-12 08:24 UTC, jcechace commented
@jpechane Also fixed a typo and added missing configuration group in `MongoDbConnectorConfig` as part of the second commit -- I figured it's ok since it is more or less a documentation as well :)

2023-09-12 09:08 UTC, jpechane requested changes

2023-09-12 17:12 UTC, jcechace commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +|The maximum allowed size of the stored document for which change events are processed. This includes both, the size before and after database operation, more specifically this limits the size of ful
It doesn't really... The property only takes effect when `curosor.oversize.handling.mode` is set to `skip`. In such case 0 would actually skip anything larger than zero -- as I would say is expected.

2023-09-12 17:12 UTC, jcechace commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +|The order used to construct the effective MongoDB aggregation stream pipeline.
OK.. I will add that info

2023-09-13 07:56 UTC, jpechane commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +|The maximum allowed size of the stored document for which change events are processed. This includes both, the size before and after database operation, more specifically this limits the size of ful
Yes, you are right, I just overcombined the fings a bit

2023-09-13 09:04 UTC, merged

2023-09-13 09:04 UTC, jpechane commented
@jcechace Applied, thanks