DBZ-6482 Document TimescaleDB SMT
debezium/debezium pull request #4928
Opened 2023-10-10 11:32 UTC by jpechane

2023-10-10 17:25 UTC, roldanbob requested changes

2023-10-10 17:25 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/timescaledb.adoc
> +<9> Indicates the usage of `pgoutput` logical decoding plug-in.
```suggestion
<9> Indicates use of the `pgoutput` logical decoding plug-in.
```

2023-10-10 17:25 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/timescaledb.adoc
> +<10> A list of all schemas containing TimescaleDB physicial tables.
```suggestion
<10> A list of all schemas that contain TimescaleDB physical tables.
```

2023-10-10 17:25 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/timescaledb.adoc
> +|The name of the TimescaleDB database from which to stream the changes.
```suggestion
|The name of the TimescaleDB database from which to stream changes.
```

2023-10-10 17:25 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/timescaledb.adoc
> +|Comma-separated list schema names that contain TimescaleDB raw (internal) data tables.
```suggestion
|Comma-separated list of schema names that contain TimescaleDB raw (internal) data tables.
```

2023-10-11 06:04 UTC, merged

2023-10-11 06:04 UTC, jpechane commented
@roldanbob Applied, thanks for the review!