Add note about including heartbeats table in publications
debezium/debezium pull request #4946
Opened 2023-10-17 20:43 UTC by dtseiler

I think it would be very helpful for the criminally dense like myself to have this explicitly stated in the documentation. What seems obvious to me know comes after nearly a week of frustration.

2023-10-18 00:09 UTC, Naros approved these changes
@roldanbob, feel free to merge this if the wording is acceptable for you.
Thanks for the PR @dtseiler.

2023-10-18 00:47 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +Note that the heartbeat table _must_ be included in your publication in order for the connector to see the heartbeat events and process them. This can be achieved either by adding it explicitly via `
```suggestion
[NOTE]
====
For the connector to detect and process events from a heartbeat table, you must add the table to the PostgreSQL publication that receives changes streamed from `pgoutput`.  
If the publication already exists before you deploy {prodname}, the connector uses the publications as defined.
If the publication is not configured to automatically replicate changes `FOR ALL TABLES` in the database, you must explicitly add the table to the publication, for example, 

`ALTER PUBLICATION  _<publicationName>_ ADD TABLE _<heartbeatTableName>_;`
====
```

2023-10-18 00:57 UTC, roldanbob requested changes
Added the content to an admonition block for enhanced visibility, and added a cross-reference to the `publication.name`configuraiton property.

2023-10-18 01:06 UTC, roldanbob approved these changes

2023-10-18 01:07 UTC, merged

2023-10-18 21:34 UTC, dtseiler commented
It looks like this merge only applies to [the "Nightly" set of documentation](https://debezium.io/documentation/reference/nightly/connectors/postgresql.html#postgresql-wal-disk-space). I'm just curious if there's any process or plan for backporting to at least [the current/stable line](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-wal-disk-space)?

2023-10-19 01:31 UTC, roldanbob commented
Typically, I think that we wouldn't backport documentation changes like this, @dtseiler. But I have no objections if we could spare others the grief that you endured. WDYT @Naros? @jpechane? Any reason not to backport this to 2.3 and/or 2.4?

2023-10-19 09:31 UTC, jpechane commented
Backported to 2.4