DBZ-7062 Fix mongodb record's value is not struct issue
debezium/debezium pull request #4956
Opened 2023-10-24 01:34 UTC by harveyyue

https://issues.redhat.com/browse/DBZ-7062

2023-10-24 01:36 UTC, harveyyue commented
Will update the new property `delete.tombstone.handling.mode` to doc

2023-10-24 03:14 UTC, harveyyue commented
@rk3rn3r Could you please review these doc change again?😊

2023-10-24 04:14 UTC, jpechane commented
@roldanbob Could you please take a look at it too?

@harveyyue I am a bit confused about the additional code changes. Why is that? It seems to be unrelated to docs changes. If it is a bugfix could you please create additional Jira and create separate commit for the bugfix? Thanks

2023-10-24 04:50 UTC, harveyyue commented
@jpechane OK, will create a separate commit for this hotfix.

2023-10-24 16:30 UTC, roldanbob requested changes

2023-10-24 16:30 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/event-flattening.adoc
> +====
```suggestion
`drop`:: The SMT removes both `DELETE` events and `TOMBSTONE`records from the stream.
`tombstone` (default):: The SMT retains `TOMBSTONE` records in the stream.
The `TOMBSTONE` record contains only the following value: `"value": "null"`.
`rewrite`:: The SMT retains the change event record in the stream and makes the following changes:

* Adds a `value` field to the record that contains the key/value pairs from the `before` field of the original record.
* Adds `+__deleted: true+` to the `value` of the record.
* Removes `TOMBSTONE` records.
+
This setting provides another way to indicate that the record has been deleted.

`rewrite-with-tombstone`:: The SMT behaves as it does when you select the `rewrite` option, except that it also retains `TOMBSTONE` records.
```

2023-10-24 16:30 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/event-flattening.adoc
> +====
Moved the note to the follow immediately after the first paragraph of the description.

2023-10-24 16:30 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
> +Note: It will be removed in further release, use xref:mongodb-extract-new-record-state-delete-tombstone-handling-mode[`delete.tombstone.handling.mode`] instead
```suggestion
This option is scheduled for removal in a future release.
In its place, use the xref:mongodb-extract-new-record-state-delete-tombstone-handling-mode[`delete.tombstone.handling.mode`] option.
```

2023-10-24 16:30 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
> +Note: It will be removed in further release, use xref:mongodb-extract-new-record-state-delete-tombstone-handling-mode[`delete.tombstone.handling.mode`] instead
```suggestion
This option is scheduled for removal in a future release.
In its place, use the xref:mongodb-extract-new-record-state-delete-tombstone-handling-mode[`delete.tombstone.handling.mode`] option.
```

2023-10-24 16:30 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/event-flattening.adoc
> +|
```suggestion
|No default
```

2023-10-24 16:30 UTC, roldanbob commented on documentation/modules/ROOT/pages/transformations/mongodb-event-flattening.adoc
> +====
```suggestion
|[[mongodb-extract-new-record-state-delete-tombstone-handling-mode]]xref:mongodb-extract-new-record-state-delete-tombstone-handling-mode[`delete.tombstone.handling.mode`]
|No default
|{prodname} generates a change event record for each `DELETE` operation. 
This setting determines how the MongoDB event flattening SMT handles `DELETE` events in the stream.

[NOTE]
====
The setting for this option takes precedence over any conflicting settings that you might configure for the deprecated xref:mongodb-extract-new-record-state-drop-tombstones[`drop.tombstones`] or xref:mongodb-extract-new-record-state-delete-handling-mode[`delete.handling.mode`] options.
====

Set one of the following options:

`drop`:: The SMT removes both `DELETE` events and `TOMBSTONE`records from the stream.
`tombstone` (default):: The SMT retains `TOMBSTONE` records in the stream.
The `TOMBSTONE` record contains only the following value: `"value": "null"`.
`rewrite`:: The SMT retains the change event record in the stream and makes the following changes:

* Adds a `value` field to the record that contains the key/value pairs from the `before` field of the original record.
* Adds `+__deleted: true+` to the `value` of the record.
* Removes `TOMBSTONE` records.
+
This setting provides another way to indicate that the record has been deleted.

`rewrite-with-tombstone`:: The SMT behaves as it does when you select the `rewrite` options, except that it also retains `TOMBSTONE` records.
```

2023-10-25 02:57 UTC, harveyyue commented
@roldanbob Done, a big thank for helping improve the doc description of this option.

2023-10-25 03:00 UTC, roldanbob commented
> @roldanbob Done, a big thank for helping improve the doc description of this option.

Oh, you're very welcome, @harveyyue! Thanks for that. I hoped that you would be in agreement with the proposed changes.

2023-10-27 09:17 UTC, merged

2023-10-27 09:17 UTC, jpechane commented
@harveyyue @roldanbob Applied, thanks guys!