DBZ-6963 Do not merge events if table has no LOB columns
debezium/debezium pull request #4964
Opened 2023-10-26 06:19 UTC by Naros

https://issues.redhat.com/browse/DBZ-6963

2023-10-26 06:19 UTC, Naros commented
/packit test --labels oracle

2023-10-26 11:52 UTC, Naros commented
/packit test --labels oracle

2023-10-27 12:02 UTC, jpechane requested changes
The test failures are in the new test so it is related.

2023-11-01 09:32 UTC, Naros commented
Oops, that's my mistake on that @jpechane.  Should be fixed now.

2023-11-01 09:32 UTC, Naros commented
/packit test --labels oracle

2023-11-08 17:38 UTC, Naros commented
/packit test --labels oracle

2023-11-09 09:58 UTC, merged

2023-11-09 09:58 UTC, jpechane commented
@Naros Applied, thanks!