[docs] for DBZ-7284
debezium/debezium pull request #5150
Opened 2024-01-11 14:36 UTC by rkudryashov

2024-01-15 13:32 UTC, jpechane commented
@roldanbob Could you please take a look? Thanks

2024-01-15 18:26 UTC, roldanbob requested changes

2024-01-15 18:26 UTC, roldanbob commented on documentation/modules/ROOT/pages/integrations/cloudevents.adoc
>  Separate the values in each pair with a colon, for example:
```suggestion
The global setting is followed by a set of pairs.
The first element in each pair specifies the name of a CloudEvent field (`id` or `type`), or the name of a data schema (`dataSchemaName`).
The second element in the pair specifies how the converter populates the value of the field.
Valid values are `generate` or `header`.
Separate the values in each pair with a colon, for example:
```

2024-01-16 07:28 UTC, merged

2024-01-16 07:29 UTC, jpechane commented
@rkudryashov @roldanbob Applied, thanks!