DBZ-7258 Enable Retry on the Debezium Storage JDBC
debezium/debezium pull request #5167
Opened 2024-01-17 12:49 UTC by ilyasahsan123

https://issues.redhat.com/browse/DBZ-7258

2024-01-17 16:29 UTC, sherpa003 requested changes

2024-01-18 08:01 UTC, ilyasahsan123 commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/offset/JdbcOffsetBackingStore.java
> +                conn.connection().close();
I'll consider it. Thanks for your recommendation.

2024-01-18 08:12 UTC, ilyasahsan123 commented on debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcConnectionIT.java
> +            conn.close();
Got it, I'll give your suggestion a shot and manually test the scenario.

2024-01-18 08:19 UTC, ilyasahsan123 commented on debezium-storage/debezium-storage-jdbc/src/test/java/io/debezium/storage/jdbc/JdbcConnectionIT.java
> +            conn.close();
hi @jpechane, do you have any suggestion for this?

2024-01-18 08:23 UTC, ilyasahsan123 commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcConnection.java
> +        return !conn.isClosed();
Got it. I'll try your recommendation. Thanks for allowing me to continue this pull request.

2024-01-24 14:28 UTC, jpechane requested changes

2024-01-24 14:28 UTC, jpechane commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java
> +    private static final Integer DEFAULT_MAX_RETRIES = 10;
```suggestion
    private static final int DEFAULT_MAX_RETRIES = 10;
```

2024-01-24 14:28 UTC, jpechane commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java
> +    private long waitRetryDelay;
```suggestion
    private Duration waitRetryDelay;
```

2024-01-24 14:28 UTC, jpechane commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java
> +    public long getWaitRetryDelay() {
```suggestion
    public Duration getWaitRetryDelay() {
```

2024-01-24 14:28 UTC, jpechane commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java
> +    public Integer getMaxRetryCount() {
```suggestion
    public int getMaxRetryCount() {
```

2024-01-24 14:28 UTC, jpechane commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcConnection.java
> +        return !conn.isClosed();
I'd recommend that there will be a template method that will accept a functional interface with JDBC code.
The template method will start TX, call the passed code and commit/rollback at the end.
If an exception is thrown the template method will recreate the connection and retry the execution.

2024-01-26 09:20 UTC, ilyasahsan123 commented
hi @jpechane @sherpa003, 
I've incorporated your suggestions. could you please take another look? 
Thanks

2024-01-29 16:00 UTC, sherpa003 commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcConnection.java
> +            if (rollback) {
this is certainly wrong. Rollback should be done only within a catch Exception block (as you can see in my example: https://github.com/sherpa003/debezium/commit/6719ed1582dfc14fb58b6708a556f90d02ea638b)

2024-01-29 16:08 UTC, sherpa003 commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcConnection.java
> +    private synchronized boolean isConnected() {
no need to have all private method synchronized when they are called from within another synchronized method

2024-01-29 16:10 UTC, sherpa003 commented on debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcConnection.java
> +            handler.apply(conn);
this is never executed again after the reconnect.

2024-01-29 16:11 UTC, sherpa003 requested changes
it seems to me that this will not work at all.

2024-02-05 16:48 UTC, sherpa003 commented
@ilyasahsan123 , could you please let me know if you are continuing on this or if I should try to create the PR by myself based on the code I shared?

2024-02-06 02:39 UTC, ilyasahsan123 commented
I apologize for delayed update on this PR. Please take over this and I will close this PR, @sherpa003 . 🙏

2024-02-06 02:39 UTC, closed without merging