DBZ-7221 refactored mongo sharded tests
debezium/debezium pull request #5174
Opened 2024-01-22 08:44 UTC by MartinMedek

2024-02-19 10:50 UTC, obabec requested changes

2024-02-19 10:50 UTC, obabec commented on debezium-testing/debezium-testing-system/src/test/java/io/debezium/testing/system/fixtures/databases/ocp/OcpMongoSharded.java
> +                .withShardCount(OcpMongoShardedConstants.SHARD_COUNT)
You are passing parameters but you are not using it.

2024-02-20 15:36 UTC, jcechace reviewed
Few comments mostly around the ability to understand when reading the code. I'm also missing javadocs

2024-02-21 09:59 UTC, MartinMedek commented on debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/mongodb/sharded/OcpMongoShardedReplicaSet.java
> +public class OcpMongoShardedReplicaSet implements Startable {
It is replica set in ocp sharded mongo cluster. I changed the naming and hope it's more clear.

2024-02-22 07:52 UTC, MartinMedek commented on debezium-testing/debezium-testing-system/src/main/java/io/debezium/testing/system/tools/databases/mongodb/sharded/MongoShardedUtil.java
> +        return "db.getSiblingDB('admin').createUser({user: '" + userName + "', pwd: '" + password + "', roles: [{role:\"root\",db:\"admin\"}] })";
Good tip, I shall investigate for future what can be replaced with the client.

2024-02-22 08:19 UTC, obabec approved these changes

2024-02-26 08:56 UTC, merged