Fixes use of outbox event router in transparent mode on debezium server
debezium/debezium pull request #5294
Opened 2024-02-19 15:14 UTC by akulapid

1. Adds support for string and binary serialization formats on debezium
      api.
    2. Enables configuring separate key and value formats on embedded engine.
    
    This change fixes the following issue using outbox event router on
    embedded engine:
    
    A common event definition consists of string keys and binary values.
    This maps well to using identifiers for keys and is flexible to
    different serialization formats like protobuf, avro etc.
    This is not possible on outbox event router on embedded engine
    currently, because of lack of support for string and binary formats and
    assumptions that key and value formats are same.
    
    This change addresses both of these issues enabling use of outbox event
    router in transparent payload mode on debezium server.

2024-02-20 12:16 UTC, jpechane requested changes
@akulapid LGTM, thanks! I think we just need to use a different format name fro string and I'd like also extend the testsuite. Other than that it is good to go.

2024-02-20 20:03 UTC, akulapid commented on debezium-api/src/main/java/io/debezium/engine/format/Str.java
> +public class Str implements SerializationFormat<String> {
This is a much nicer name! I have made this change

2024-02-20 20:04 UTC, akulapid commented on documentation/modules/ROOT/pages/operations/debezium-server.adoc
> +|The name of the output format for key, one of `json`/`jsonbytearray`/`avro`/`protobuf`/`str`/`binary`.
This is now changed to `simplestring` because server does getSimpleName() of the format class

2024-02-27 04:13 UTC, akulapid commented
Hi @jpechane, wondering if you had a chance to review the new changes?

2024-02-29 14:17 UTC, jpechane approved these changes
@akulapid LGTM, thanks! I'll merge the PRs when the CI run is finished.

2024-03-01 04:36 UTC, akulapid commented
I see some CI checks failing but they seem to be unrelated to this change. Please let me know if something is needed from my side

2024-03-01 07:23 UTC, merged

2024-03-01 07:23 UTC, jpechane commented
@akulapid Applied, thanks!

2024-03-01 07:24 UTC, jpechane commented
Could you pease prepare a separate PR with docs update? Thanks

2024-03-02 06:46 UTC, akulapid commented
Thanks very much! There's doc changes included in this commit itself. If there's something specific you're thinking about let me know, will be happy to raise another PR

2024-03-05 07:33 UTC, jpechane commented
@akulapid You are right, it is exactly there. I somehow forgot about it while I was doing the last review, sorry for the confusion.