DBZ-7305 Update Db2 doc for snapshot modes alignment
debezium/debezium pull request #5367
Opened 2024-03-11 09:23 UTC by mfvitale

related to: https://github.com/debezium/debezium-connector-db2/pull/142

2024-03-11 15:14 UTC, roldanbob requested changes
@mfvitale A few small suggestions. Otherwise, LGTM. Thanks!

2024-03-11 15:14 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/db2.adoc
> +| When xref:db2-property-snapshot-query-mode[`snapshot.query.mode`] is set to `custom`, use this setting to specify the name of the custom implementation provided in the `name()` method that is defin
```suggestion
| When xref:db2-property-snapshot-query-mode[`snapshot.query.mode`] is set to `custom`, use this setting to specify the name of the custom query implementation provided in the `name()` method that is defined by the 'io.debezium.spi.snapshot.SnapshotQuery' interface.
```

2024-03-12 10:03 UTC, mfvitale commented
@roldanbob thanks! Proposed changes addressed.

2024-03-12 13:47 UTC, roldanbob reviewed
LGTM! Thanks.

2024-03-14 05:51 UTC, merged