DBZ-7497 Document configuration based snapshot mode
debezium/debezium pull request #5425
Opened 2024-03-26 14:38 UTC by mfvitale

related to: https://github.com/debezium/debezium/pull/5422

2024-03-26 16:56 UTC, roldanbob requested changes
Proposed suggestions and one set of questions wrt the use case for `snapshot.mode.configuration.based.snapshot.on.data.error`.

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mongodb.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
Same question as earlier.

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|The `configuration_based` snapshot mode allows control over snapshots by setting connectors properties prefixed with 'snapshot.mode.configuration.based'.
```suggestion
|Set the snapshot mode to `configuration_based` to control snapshot behavior through the set of connector properties that have the prefix 'snapshot.mode.configuration.based'.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|The `configuration_based` snapshot mode allows control over snapshots by setting connectors properties prefixed with 'snapshot.mode.configuration.based'.
```suggestion
|Set the snapshot mode to `configuration_based` to control snapshot behavior through the set of connector properties that have the prefix 'snapshot.mode.configuration.based'.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes the table schema when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the stream should start or not after snapshot.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector begins to stream change events after a snapshot completes.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not in case schema history topic is missing.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table schema in a snapshot if the schema history topic is not available.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data in a snapshot in the event that data is no longer available in the transaction log.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/oracle.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/oracle.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes the table schema when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes the table schema when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes the table schema when it performs a snapshot.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the stream should start or not after snapshot.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector begins to stream change events after a snapshot completes.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/oracle.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the stream should start or not after snapshot.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector begins to stream change events after a snapshot completes.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the stream should start or not after snapshot.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector begins to stream change events after a snapshot completes.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/oracle.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not in case schema history topic is missing.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table schema in a snapshot if the schema history topic is not available.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not in case schema history topic is missing.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table schema in a snapshot if the schema history topic is not available.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the schema should be snapshotted or not in case schema history topic is missing.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table schema in a snapshot if the schema history topic is not available.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/sqlserver.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data in a snapshot in the event that data is no longer available in the transaction log.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/oracle.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data in a snapshot in the event that data is no longer available in the transaction log.
```

2024-03-26 16:56 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
```suggestion
|If the `snapshot.mode` is set to `configuration_based`, set this property to specify whether the connector includes table data in a snapshot in the event that data is no longer available in the transaction log.
```

2024-03-27 08:47 UTC, mfvitale commented on documentation/modules/ROOT/pages/connectors/db2.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
This regard the last commited offset. If it is not available on the log (ie. purged), set this property to `true` permits to re do a snapshot.

2024-03-27 13:36 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/db2.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
Ok, thanks for the clarification. I've made some changes. WDYT?

2024-03-27 13:38 UTC, mfvitale commented on documentation/modules/ROOT/pages/connectors/db2.adoc
> +|When `snapshot.mode` is set as `configuration_based`, this setting permits to specify whenever the data should be snapshotted or not in case data is no more present on db log.
@roldanbob Sounds good!

2024-03-27 23:28 UTC, roldanbob approved these changes
LGTM

2024-03-28 08:12 UTC, merged