DBZ-7138 Additional Conditions for MongoDb Incremental Snapshot
debezium/debezium pull request #5488
Opened 2024-04-17 09:23 UTC by ani-sha

- [ ] Add documentation

closes https://issues.redhat.com/browse/DBZ-7138

2024-04-17 10:51 UTC, mfvitale commented on debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java
> +        return context.currentDataCollectionId().getAdditionalCondition().map(s -> s.substring(1, s.length() - 1)).orElse("");
WDYT to put ```s -> s.substring(1, s.length() - 1)``` in a method with a meaningful name?

2024-04-17 10:52 UTC, mfvitale commented
@ani-sha LGTM, I leaved just a minor comment.

2024-04-22 09:33 UTC, jcechace requested changes
Small nitpick as pointed out by @mfvitale

2024-04-22 09:36 UTC, jcechace commented
@jpechane  should we also backport this to 2.6?

2024-04-23 12:37 UTC, jpechane commented
@jcechace No, this is technically new feature so there will be no backport

2024-04-23 12:38 UTC, merged