DBZ-7820 Adding documentation for Postgres custom data type converters
debezium/debezium pull request #5515
Opened 2024-04-25 19:04 UTC by zeldanerd24

https://issues.redhat.com/browse/DBZ-7820

2024-04-25 19:19 UTC, Naros reviewed
This LGTM ,can you review @roldanbob as time permits.

2024-04-26 03:10 UTC, roldanbob requested changes
Thanks, @zeldanerd24! A few items for your consideration. Let me know if you have any questions.

2024-04-26 03:10 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +* The type of value passed to the converter will vary based on the logical decoding output plug-in
```suggestion
* The type of value that is passed to the converter depends on the logical decoding output plug-in that is configured for the replication slot.
```

2024-04-26 03:10 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +** `pgoutput` will get a string representation of the column data
```suggestion
** `decoderbufs` passes a byte array (`byte[]`) representation of the column data.
** `pgoutput` passes a string representation of the column data.
```

2024-04-29 09:22 UTC, merged

2024-04-29 09:23 UTC, jpechane commented
@zeldanerd24 Applied, thanks