DBZ-4332 Add `row_id` to Oracle event's source info block
debezium/debezium pull request #5524
Opened 2024-04-26 19:02 UTC by Naros

https://issues.redhat.com/browse/DBZ-4332

2024-04-26 19:27 UTC, Naros commented
/packit test --labels oracle

2024-04-29 11:05 UTC, jpechane requested changes
@Naros LGTM, thanks! I left two comments related naming and exception handling. When addressed please feel free to merge youself.

2024-04-29 11:05 UTC, jpechane commented on debezium-core/src/main/java/io/debezium/relational/Column.java
> +    boolean isInvisible();
I wonder if using the name `invisible` is correct. IMHO `INVISIBLE`  columns in Oracle, MySQL etc. is something completely different and we are processing them. Is not `ROWID` pseudo (synthetic) column, not invisible?

2024-04-29 11:05 UTC, jpechane commented on debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
> +            e.printStackTrace();
Please use `LOGGER`

2024-04-29 17:41 UTC, Naros commented on debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
> +            e.printStackTrace();
Oops, that was not intended :)

2024-04-29 21:02 UTC, Naros commented
/packit test --abels oracle

2024-04-30 06:58 UTC, jpechane commented
/packit test --labels oracle

2024-04-30 06:59 UTC, jpechane approved these changes
@Naros LGTM, thanks! Feel free to merge as soon as CI passes.

2024-04-30 19:58 UTC, Naros commented
/packit test --labels oracle

2024-05-01 12:47 UTC, Naros commented
/packit test --labels oracle

2024-05-01 13:54 UTC, Naros commented
/packit test --labels oracle

2024-05-01 19:37 UTC, Naros commented
Looking into the failures, they seem to be related to the changes.

2024-05-02 22:25 UTC, Naros commented
@jpechane, after investigating the failures, I've changed to focus only on streaming.

The changes needed to handle snapshots were starting to grow tendrils into the schema history topic and requiring some changes there that are better served as a design discussion before proceeding rather than to try and shoehorn a solution that may not be ideal without discussion.

2024-05-02 22:32 UTC, Naros commented
/packit test --labels oracle

2024-05-03 12:33 UTC, jpechane commented
@Naros `OracleSchemaMigrationIT` failure is unrelated?

2024-05-03 13:37 UTC, Naros commented
> @Naros `OracleSchemaMigrationIT` failure is unrelated?

I don't think so, i just reran that class locally against 21-xs and it passed all green, so I'd say it's likely timing:
![image](https://github.com/debezium/debezium/assets/3255568/bc9635b6-c310-469e-95ea-a6bd28dc5dd6)

2024-05-06 08:40 UTC, merged

2024-05-06 08:40 UTC, jpechane commented
@Naros Applied, thanks!