DBZ-7570 docs update for use.nongraceful.disconnect config
debezium/debezium pull request #5525
Opened 2024-04-29 07:03 UTC by acristu

Related PRs:
https://github.com/osheroff/mysql-binlog-connector-java/pull/142
https://github.com/debezium/debezium/pull/5517

2024-04-29 08:47 UTC, jpechane commented
@roldanbob Could you please check the wording and merge if it is OK? Thanks

2024-04-29 15:19 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/mysql.adoc
> +|A Boolean value that specifies whether the binlog client keepalive thread should use SO_LINGER with 0 timeout when terminating a stale connection. The goal is to avoid potential deadlock in `SSLSock
```suggestion
|A Boolean value that specifies whether the binary log client's keepalive thread sets the `SO_LINGER` socket option to  `0` to immediately close stale TCP connections. 
Set the value to `true` if the connector experiences deadlocks in `SSLSocketImpl.close`.
ifdef::community[]
For more information, see https://github.com/osheroff/mysql-binlog-connector-java/issues/133 .
endif::community[]
```

2024-04-29 15:36 UTC, roldanbob requested changes
@jpechane @acristu @Naros Please take a look and let me know if these changes are ok. 
I conditionalized the external link for upstream use only, bc it seemed like TMI for the product version. Do you concur?

2024-04-29 17:40 UTC, Naros commented
Hi @roldanbob we most definitely should conditionalize the link to the binlog client repository for downstream builds, so I do concur with the suggestion :+1:

2024-04-30 07:21 UTC, jpechane commented
Closing, changes incorporated via https://github.com/debezium/debezium/pull/5529

Thanks!

2024-04-30 07:21 UTC, closed without merging