DBZ-4332 Update documentation about `row_id`
debezium/debezium pull request #5527
Opened 2024-04-29 18:41 UTC by Naros

https://issues.redhat.com/browse/DBZ-4332

Sibling PR for https://github.com/debezium/debezium/pull/5524

2024-04-30 07:23 UTC, jpechane approved these changes
LGTM!
@roldanbob Any comments on this one?

2024-04-30 13:15 UTC, roldanbob requested changes
Slight edit, but otherwise LGTM.

2024-04-30 13:15 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/oracle.adoc
> +Consequently, the {prodname} connector for Oracle will consistently display empty `row_id` values in the source information block when utilizing the OpenLogReplicator adapter.
```suggestion
Consequently, in environments that use the OpenLogReplicator adapter, the {prodname} connector for Oracle consistently displays empty `row_id` values in the source information block.
```

2024-05-01 17:03 UTC, roldanbob approved these changes

2024-05-06 08:41 UTC, merged