DBZ-8063 Add documentation for webhook auth config
debezium/debezium pull request #5681
Opened 2024-07-15 16:04 UTC by TimoWilhelm

Update documentation of config options for Standard Webhooks authentication.

Main PR: https://github.com/debezium/debezium-server/pull/108

2024-07-15 18:49 UTC, Naros reviewed
Overall LGTM, just asked Bob for a quick cursory review.

2024-07-15 21:16 UTC, roldanbob requested changes
A few small suggestions.
Also, please adhere to the standard of entering each sentence on its own line.
Doing so makes the doc sources easier to read and it also make it easier to manage diffs.
It's true that this was not always done, but it's the preferred format for all newly added content.
Thanks!

2024-07-16 06:53 UTC, TimoWilhelm commented
Thanks for the review! I updated the docs with the suggestions.

2024-07-16 13:18 UTC, roldanbob requested changes
Hi @TimoWilhelm. Thanks for your quick response. I noticed a couple of further instances where we need minor changes.

2024-07-16 13:18 UTC, roldanbob commented on documentation/modules/ROOT/pages/operations/debezium-server.adoc
> +If you omit this property, the HTTP client sink will not use any authentication headers for the connection.
```suggestion
If you omit this property, the HTTP client sink does not use authentication headers for the connection.
```

2024-07-16 13:18 UTC, roldanbob commented on documentation/modules/ROOT/pages/operations/debezium-server.adoc
> +|The webhooks signing secret that {prodname} uses to generate HMAC-SHA256 signatures of the webhook request.
```suggestion
|The webhooks signing secret that {prodname} uses to generate HMAC-SHA256 signatures for the webhook request. 
```

2024-07-16 13:18 UTC, roldanbob commented on documentation/modules/ROOT/pages/operations/debezium-server.adoc
> +For more information about implementing or validating Webhook signatures, see the link:https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md[Standard Webhooks spe
```suggestion
For more information about implementing or validating webhook signatures, see the link:https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md[Standard Webhooks specification]. 
```
In general, when "webhooks" is not part of a title or heading, and does not refer to a particular company or product, the lower case is the accepted form.

2024-07-16 13:18 UTC, roldanbob commented on documentation/modules/ROOT/pages/operations/debezium-server.adoc
> +If you omit this property, the HTTP client sink will not use any authentication headers for the connection.
Write in the simple present tense as much a possible.

2024-07-16 15:42 UTC, TimoWilhelm commented
@roldanbob Thanks, I applied the suggested changes.

2024-07-16 15:46 UTC, roldanbob approved these changes
LGTM, @TimoWilhelm Thanks for your efforts and patience!

2024-07-17 07:37 UTC, mfvitale commented on documentation/modules/ROOT/pages/operations/debezium-server.adoc
> +|[[httpclient-authentication-webhook-secret]]<<httpclient-authentication-webhook-secret, `debezium.sink.http.webhook.secret` >>
@TimoWilhelm  Looking at the code this seems should be `debezium.sink.http.authentication.webhook.secret`. Ins't it?

2024-07-17 08:14 UTC, mfvitale approved these changes

2024-07-17 12:21 UTC, merged