DBZ-8086 The MySqlParser.g4 parser supports statement as field name
debezium/debezium pull request #5705
Opened 2024-07-22 15:51 UTC by caicancai

2024-07-22 15:53 UTC, caicancai commented
@Naros @jpechane PATL, thank you

2024-07-22 16:00 UTC, Naros commented
Hi @caicancai does this also apply to MariaDB?

2024-07-22 16:03 UTC, caicancai commented
> Hi @caicancai does this also apply to MariaDB? If so, could you amend the MariaDB Parser & its tests, too?
Unfortunately, I don't have a MariaDB test environment.

2024-07-22 16:25 UTC, Naros requested changes

2024-07-22 16:25 UTC, Naros commented on debezium-ddl-parser/src/test/resources/mysql/examples/dml_select.sql
> +SELECT REPLACE(statement, ' ','') as statement from your_table;
So I'm a bit confused, I added this to the MySQL `dml_select.sql` without modifying the grammar, and this works without an error, see this:
```
#begin
-- statement is supported as the field name
SELECT REPLACE(statement, ' ','') as statement from your_table;
#end
```
Did you check whether the DDL parser failed without making changes to the grammar?

2024-07-22 16:25 UTC, Naros commented on debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
> +    | STATEMENT
I also don't believe this is the right place for this change, it should be part of `keywordsCanBeId` rule.

Furthermore, this `keywordsCanBeId` already includes the `STATEMENT` keyword as it was added sometime ago specifically for MariaDB, so I don't think this change is needed based on the current `main` code base.

I would again redirect you to my above inquiry, does the DDL tests pass by simply adding the SQL but no change to the grammar.

2024-07-25 05:24 UTC, Naros commented
Hi @caicancai, I'm following up to see if you concur with my assessment above.
Can we close this pull request?

2024-07-25 06:42 UTC, caicancai commented
> 你好@caicancai，我正在跟进，看看您是否同意我上述的评估。 我们可以关闭此拉取请求吗？

Yes，I'm sorry that I can't follow up due to my recent busy schedule. Thank you for your follow-up.

2024-07-25 06:43 UTC, caicancai commented
> 你好@caicancai，我正在跟进，看看您是否同意我上述的评估。 我们可以关闭此拉取请求吗？

Yes，I'm sorry that I can't follow up due to my recent busy schedule. Thank you for your follow-up.

2024-07-25 06:43 UTC, closed without merging