DBZ-8121 Document pgvector
debezium/debezium pull request #5737
Opened 2024-08-05 12:18 UTC by jpechane

2024-08-05 16:58 UTC, roldanbob requested changes
Restructured the Notes description. Does this work?

2024-08-05 16:58 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +=== PgVector types
```suggestion
=== pgvector types
```

2024-08-05 16:58 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +.Mappings of pgvector data types
```suggestion
.Mappings of PostgreSQL `pgvector` data types
```

2024-08-05 16:58 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> +* `vector (MAP (INT16, FLOAT64))` - A map representing the sparse vector. Each value is is a combination of index of vector element (starting with `1`) and the value of the element.
```suggestion
Contains a structure that includes the following fields: 

`dimensions (INT16)`:: The total length of the sparse vector.
`vector (MAP (INT16, FLOAT64))`:: A map that represents the sparse vector.  +
Each map value includes the following elements:

* Index number of the vector element (starting with `1`).
* Value of the vector element.
```

2024-08-05 16:58 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/postgresql.adoc
> + +
```suggestion
|`io.debezium.data.SparseVector` 
 
```

2024-08-06 04:06 UTC, jpechane commented
@roldanbob Thanks for the review!

2024-08-06 12:20 UTC, merged