DBZ-7291 Retry flush if failed with retriable exceptions each Dialect.
debezium/debezium pull request #5854
Opened 2024-09-13 15:00 UTC by Naros

https://issues.redhat.com/browse/DBZ-7291

Port of the PR from https://github.com/debezium/debezium-connector-jdbc/pull/55 after moving the repository.

2024-09-13 16:12 UTC, roldanbob requested changes
Hey @Naros I've proposed a few small changes. Let me know what you think. Thanks.

2024-09-13 16:12 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/jdbc.adoc
> +|Specifies the number of milliseconds to wait in between flush attempts when a flush operation fails and is scheduled to be retried.
```suggestion
|Specifies the number of milliseconds that the connector waits to retry a flush operation that failed.
```

2024-09-13 16:12 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/jdbc.adoc
> +|Specifies the number of milliseconds to wait in between flush attempts when a flush operation fails and is scheduled to be retried.
I think readers can infer that the value applies only if the operation is scheduled to be retried. If you disagree, we can restore that clause.

2024-09-13 16:12 UTC, roldanbob commented on documentation/modules/ROOT/pages/connectors/jdbc.adoc
> +|Specifies the maximum number of attempts to flush changes to the target database on specific database errors.
I'm not strongly attached to it, but I'm inclined to say "certain" vs. "specific" in the absence of information about exactly which errors might cause the failure.  To my mind, "certain" is more open-ended, whereas "specific" leads me to expect that we enumerate those errors somewhere.

2024-09-16 14:40 UTC, roldanbob approved these changes
LGTM!

2024-09-17 12:55 UTC, merged

2024-09-17 12:55 UTC, jpechane commented
@Naros Applied, thanks!

2024-09-19 12:18 UTC, mfvitale commented
Since a combination of settings of these new retry configs can interfere with the `max.poll.interval.ms` causing a re-balance, should we add a note on the docs about it?

2024-09-19 12:19 UTC, jpechane commented
@mfvitale Good idea

2024-09-19 12:32 UTC, mfvitale commented
@Naros If you don't mind I'll can do it.