Dbz 8281 Provide outbox Quarkus devservice
debezium/debezium pull request #5903
Opened 2024-09-29 15:47 UTC by dcdh

2024-09-29 15:49 UTC, dcdh commented on debezium-quarkus-outbox-common/deployment/src/main/java/io/quarkus/kafka/client/deployment/RedpandaKafkaContainer.java
> +/*
hack, will remove it when changed will be pushed and release inside Quarkus
Keep pr in draft until done

2024-10-03 05:01 UTC, Naros requested changes
I've left a few inline comments @dcdh, if you could take a look.
If you could also rebase the PR, we'd appreciate it.

2024-10-03 05:01 UTC, Naros commented on debezium-quarkus-test-outbox/src/main/java/io/debezium/outbox/test/quarkus/remote/DebeziumConnectorStatus.java
> +public record DebeziumConnectorStatus(String name, Connector connector) {
Could use some documentation.

2024-10-03 05:01 UTC, Naros commented on debezium-quarkus-test-outbox/src/main/java/io/debezium/outbox/test/quarkus/remote/RemoteConnectorApi.java
> +public interface RemoteConnectorApi {
Can we document the purpose and use of this API.

2024-10-05 12:27 UTC, dcdh commented on debezium-quarkus-outbox-common/deployment/src/main/java/io/quarkus/kafka/client/deployment/RedpandaKafkaContainer.java
> +/*
https://github.com/quarkusio/quarkus/pull/43582

2024-10-05 12:32 UTC, dcdh commented on debezium-quarkus-outbox-reactive/integration-tests/src/main/resources/application.properties
> +#quarkus.debezium-outbox.payload.type=com.vladmihalcea.hikbernate.type.json.JsonNodeBinaryType
Yes it is a typo. I did not see it.
Thanks for reporting it

2024-10-05 13:36 UTC, dcdh commented
@Naros 

Thanks for reviewing this PR. I have resolved all of your comments.

Inside `DebeziumConnectorStatus` I have removed `state()` method because it is not used.

I forget to do little commits for the review instead I rewrite them. I am sorry...

Documentation has been generated using chatgpt, lot easier way.

Regards,
Damien

2026-01-06 13:59 UTC, Naros commented
:x: Developer Certificate of Origin (DCO) check failed.

Hi @dcdh, please sign off all commits with:

```
git commit -s
```

If pull request commits are not signed off, the pull request cannot be merged. For more information about why this is required, please see [our blog](https://debezium.io/blog/2025/12/12/contribution-requirements-changing/) about contribution requirement changes.

2026-08-04 01:24 UTC, Naros commented
Thank you for your contribution.

This pull request is being closed due to extended inactivity. If you would like to continue working on this, please feel free to reopen this pull request or submit a new one against the latest main branch. We appreciate your interest in improving Debezium.

2026-08-04 01:24 UTC, closed without merging