[WIP] DBZ-8336 Error Handling Mode for ReselectColumnsPostProcessor
debezium/debezium pull request #5944
Opened 2024-10-18 08:22 UTC by gaurav7261

2024-10-28 08:15 UTC, gaurav7261 commented
@Naros can you please review

2024-10-29 05:30 UTC, Naros requested changes
Thanks @gaurav7261, a few inline suggestions, please.

2024-10-29 05:30 UTC, Naros commented on documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
> +|Specifies whether the post processor reselects behaviour if reselection fail or give empty record. +
```suggestion
|Specifies how the reselect post processor reacts to certain conditions. +
```

2024-10-29 05:30 UTC, Naros commented on documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
> +By default, it only logs the error in case reselection fail or empty. +
```suggestion
By default, the post-processor logs a warning message when the row cannot be found or if there is a database selection error. +
```

2024-10-29 05:30 UTC, Naros commented on documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
> +You can set this property to `FAIL` to fail the connector in case of reselection fail or empty record.
```suggestion
When set to `FAIL`, the connector will stop processing changes if the row no longer exists at the time of reselection or if there is a database failure when reselecting the row.
```

2024-10-29 05:30 UTC, Naros commented on documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
> +|Log or fail the connector in  case reselection fail or give empty record.
Log a warning or throw an exception when reselection does not find the row or if a database exception is raised.

2024-10-29 05:30 UTC, Naros commented on debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
> +                }
```suggestion
                if (errorHandlingMode == ErrorHandlingMode.FAIL) {
                    throw new DebeziumException("Failed to find row in table " + tableId + " with key " + key);
                }
                LOGGER.warn("Failed to find row in table {} with key {}.", tableId, key);
                return;
```

2024-10-29 05:30 UTC, Naros commented on debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
> +            }
```suggestion
            if (errorHandlingMode == ErrorHandlingMode.FAIL) {
                throw new DebeziumException("Failed to re-select columns for table " + tableId + " and key " + keyValues, e);
            }
            LOGGER.warn("Failed to re-select columns for table {} and key {}", tableId, keyValues, e);
            return;
```

2024-10-29 21:58 UTC, gaurav7261 commented
Hi @Naros, all review changes are done, thanks for reviewing

2024-11-08 04:03 UTC, gaurav7261 commented
@Naros  can you please review this

2025-01-20 14:47 UTC, gaurav7261 commented
@Naros  can you please review this

2025-01-21 22:22 UTC, Naros approved these changes
Overall LGTM, I've rebased against `main` to check CI.

2025-01-22 01:35 UTC, merged