DBZ-7245 Add documentation for File Signal Channel
debezium/debezium pull request #5981
Opened 2024-11-11 09:18 UTC by ani-sha

https://issues.redhat.com/browse/DBZ-7245

2024-11-11 16:16 UTC, mfvitale commented
LGTM, @ani-sha . 

@roldanbob can have a look? Thanks.

2024-11-11 16:17 UTC, mfvitale approved these changes

2024-11-11 16:58 UTC, roldanbob requested changes
@ani-sha @mfvitale I've made a couple of suggestions and also raised a couple of questions.

2024-11-12 08:11 UTC, ani-sha commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +== Enabling a File Signal Channel
That's a question for @jpechane. Do we have any plans?

2024-11-12 08:37 UTC, jpechane commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +== Enabling a File Signal Channel
No, definitely not in the short term.

2024-11-12 20:57 UTC, Naros commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +If you want to use a different file, you can specify the file name by setting the `signal.file` property in the connector configuration.
Hi @roldanbob, the default location (path) is the root of the connector's classpath. If the user supplies the `signal.file` property, the property can refer to any accessible path & file available to the environment, which you would generally do in almost all situations, I would imagine.

2024-11-13 05:26 UTC, ani-sha commented
Thanks @roldanbob! Added the changes.

2024-11-13 06:06 UTC, merged

2024-11-13 06:06 UTC, jpechane commented
@ani-sha Applied, thanks