DBZ-7856 Remove signal offset support for KafkaSignalChannel
debezium/debezium pull request #6028
Opened 2024-12-03 09:46 UTC by mfvitale

closes: https://issues.redhat.com/browse/DBZ-7856

2024-12-03 15:57 UTC, roldanbob requested changes
@mfvitale Here you go. For the second sentence, can we offer some concrete suggestion on how someone might monitor signal progress?

2024-12-03 15:57 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +This means that is up to you to monitor whenever a signal completed correctly or not.
```suggestion
With the exception of the `source` channel, {prodname} signaling channels do not implement retry policies.
After you initiate a signal, be sure to verify whether it completes successfully.
```
Is there any specific external automatic monitoring mechanism that a user could implement?

2024-12-03 15:57 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +
```suggestion
[id="debezium-signaling-error-handling"]
```

2024-12-04 14:32 UTC, roldanbob requested changes
Oh, I should have thought of that, @mfvitale! Yes, that's perfect. I modified the text a little. If you're ok with the changes, I think we can merge this. Thanks!

2024-12-04 14:32 UTC, roldanbob commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +You can set up {link-prefix}:{link-notification}[notification] to monitor the progress of incremental/blocking snapshots.
```suggestion
You can enable a connector to automatically report on the the progress of incremental or blocking snapshots by configuring it to send {link-prefix}:{link-notification}[notifications].
```

2024-12-04 14:51 UTC, mfvitale commented on documentation/modules/ROOT/pages/configuration/signalling.adoc
> +You can set up {link-prefix}:{link-notification}[notification] to monitor the progress of incremental/blocking snapshots.
Done. Thanks for the suggestions.

2024-12-04 14:54 UTC, roldanbob approved these changes
LGTM! Thanks.

2024-12-05 11:59 UTC, merged

2024-12-05 11:59 UTC, jpechane commented
@mfvitale Applied, thanks!